class Country {
  String name;
  String dialCode;
  String isoCode;

  Country.empty()
      : name = '',
        dialCode = "",
        isoCode = '';

  Country.isoCode(String isoCode)
      : name = '',
        dialCode = "",
        isoCode = '' {
    Country? country = Countries.list.firstWhere(
        (element) => element.isoCode == isoCode,
        orElse: () => Country.empty());
    name = country.name;
    dialCode = country.dialCode;
    isoCode = country.isoCode;
  }

  Country.dialCode(String dialCode)
      : name = '',
        dialCode = "",
        isoCode = '' {
    Country? country = Countries.list.firstWhere(
        (element) => element.dialCode == dialCode,
        orElse: () => Country.empty());
    name = country.name;
    dialCode = country.dialCode;
    isoCode = country.isoCode;
  }

  Country.from(Map<String, String> map)
      : name = map['name'] ?? '',
        dialCode = map['dialCode'] ?? '',
        isoCode = map['isoCode'] ?? '';
}
class Countries {
  static List<Country> get list => _list;
  static List<Country> get tr => _tr;
  static List<Country> get de => _de;
  static List<Country> get es => _es;
  static List<Country> get hi => _hi;
  static List<Country> get zh => _zh;

  static final List<Country> _list = [
    {"name": "Afghanistan", "dialCode": "+93", "isoCode": "AF"},
    {"name": "Aland Islands", "dialCode": "+358", "isoCode": "AX"},
    {"name": "Albania", "dialCode": "+355", "isoCode": "AL"},
    {"name": "Algeria", "dialCode": "+213", "isoCode": "DZ"},
    {"name": "AmericanSamoa", "dialCode": "+1684", "isoCode": "AS"},
    {"name": "Andorra", "dialCode": "+376", "isoCode": "AD"},
    {"name": "Angola", "dialCode": "+244", "isoCode": "AO"},
    {"name": "Anguilla", "dialCode": "+1264", "isoCode": "AI"},
    {"name": "Antarctica", "dialCode": "+672", "isoCode": "AQ"},
    {"name": "Antigua and Barbuda", "dialCode": "+1268", "isoCode": "AG"},
    {"name": "Argentina", "dialCode": "+54", "isoCode": "AR"},
    {"name": "Armenia", "dialCode": "+374", "isoCode": "AM"},
    {"name": "Aruba", "dialCode": "+297", "isoCode": "AW"},
    {"name": "Australia", "dialCode": "+61", "isoCode": "AU"},
    {"name": "Austria", "dialCode": "+43", "isoCode": "AT"},
    {"name": "Azerbaijan", "dialCode": "+994", "isoCode": "AZ"},
    {"name": "Bahamas", "dialCode": "+1242", "isoCode": "BS"},
    {"name": "Bahrain", "dialCode": "+973", "isoCode": "BH"},
    {"name": "Bangladesh", "dialCode": "+880", "isoCode": "BD"},
    {"name": "Barbados", "dialCode": "+1246", "isoCode": "BB"},
    {"name": "Belarus", "dialCode": "+375", "isoCode": "BY"},
    {"name": "Belgium", "dialCode": "+32", "isoCode": "BE"},
    {"name": "Belize", "dialCode": "+501", "isoCode": "BZ"},
    {"name": "Benin", "dialCode": "+229", "isoCode": "BJ"},
    {"name": "Bermuda", "dialCode": "+1441", "isoCode": "BM"},
    {"name": "Bhutan", "dialCode": "+975", "isoCode": "BT"},
    {
      "name": "Bolivia, Plurinational State of",
      "dialCode": "+591",
      "isoCode": "BO"
    },
    {"name": "Bosnia and Herzegovina", "dialCode": "+387", "isoCode": "BA"},
    {"name": "Botswana", "dialCode": "+267", "isoCode": "BW"},
    {"name": "Brazil", "dialCode": "+55", "isoCode": "BR"},
    {
      "name": "British Indian Ocean Territory",
      "dialCode": "+246",
      "isoCode": "IO"
    },
    {"name": "Brunei Darussalam", "dialCode": "+673", "isoCode": "BN"},
    {"name": "Bulgaria", "dialCode": "+359", "isoCode": "BG"},
    {"name": "Burkina Faso", "dialCode": "+226", "isoCode": "BF"},
    {"name": "Burundi", "dialCode": "+257", "isoCode": "BI"},
    {"name": "Cambodia", "dialCode": "+855", "isoCode": "KH"},
    {"name": "Cameroon", "dialCode": "+237", "isoCode": "CM"},
    {"name": "Canada", "dialCode": "+1", "isoCode": "CA"},
    {"name": "Cape Verde", "dialCode": "+238", "isoCode": "CV"},
    {"name": "Cayman Islands", "dialCode": "+ 345", "isoCode": "KY"},
    {"name": "Central African Republic", "dialCode": "+236", "isoCode": "CF"},
    {"name": "Chad", "dialCode": "+235", "isoCode": "TD"},
    {"name": "Chile", "dialCode": "+56", "isoCode": "CL"},
    {"name": "China", "dialCode": "+86", "isoCode": "CN"},
    {"name": "Christmas Island", "dialCode": "+61", "isoCode": "CX"},
    {"name": "Cocos (Keeling) Islands", "dialCode": "+61", "isoCode": "CC"},
    {"name": "Colombia", "dialCode": "+57", "isoCode": "CO"},
    {"name": "Comoros", "dialCode": "+269", "isoCode": "KM"},
    {"name": "Congo", "dialCode": "+242", "isoCode": "CG"},
    {
      "name": "Congo, The Democratic Republic of the Congo",
      "dialCode": "+243",
      "isoCode": "CD"
    },
    {"name": "Cook Islands", "dialCode": "+682", "isoCode": "CK"},
    {"name": "Costa Rica", "dialCode": "+506", "isoCode": "CR"},
    {"name": "Cote d'Ivoire", "dialCode": "+225", "isoCode": "CI"},
    {"name": "Croatia", "dialCode": "+385", "isoCode": "HR"},
    {"name": "Cuba", "dialCode": "+53", "isoCode": "CU"},
    {"name": "Cyprus", "dialCode": "+357", "isoCode": "CY"},
    {"name": "Czech Republic", "dialCode": "+420", "isoCode": "CZ"},
    {"name": "Denmark", "dialCode": "+45", "isoCode": "DK"},
    {"name": "Djibouti", "dialCode": "+253", "isoCode": "DJ"},
    {"name": "Dominica", "dialCode": "+1767", "isoCode": "DM"},
    {"name": "Dominican Republic", "dialCode": "+1849", "isoCode": "DO"},
    {"name": "Ecuador", "dialCode": "+593", "isoCode": "EC"},
    {"name": "Egypt", "dialCode": "+20", "isoCode": "EG"},
    {"name": "El Salvador", "dialCode": "+503", "isoCode": "SV"},
    {"name": "Equatorial Guinea", "dialCode": "+240", "isoCode": "GQ"},
    {"name": "Eritrea", "dialCode": "+291", "isoCode": "ER"},
    {"name": "Estonia", "dialCode": "+372", "isoCode": "EE"},
    {"name": "Ethiopia", "dialCode": "+251", "isoCode": "ET"},
    {
      "name": "Falkland Islands (Malvinas)",
      "dialCode": "+500",
      "isoCode": "FK"
    },
    {"name": "Faroe Islands", "dialCode": "+298", "isoCode": "FO"},
    {"name": "Fiji", "dialCode": "+679", "isoCode": "FJ"},
    {"name": "Finland", "dialCode": "+358", "isoCode": "FI"},
    {"name": "France", "dialCode": "+33", "isoCode": "FR"},
    {"name": "French Guiana", "dialCode": "+594", "isoCode": "GF"},
    {"name": "French Polynesia", "dialCode": "+689", "isoCode": "PF"},
    {"name": "Gabon", "dialCode": "+241", "isoCode": "GA"},
    {"name": "Gambia", "dialCode": "+220", "isoCode": "GM"},
    {"name": "Georgia", "dialCode": "+995", "isoCode": "GE"},
    {"name": "Germany", "dialCode": "+49", "isoCode": "DE"},
    {"name": "Ghana", "dialCode": "+233", "isoCode": "GH"},
    {"name": "Gibraltar", "dialCode": "+350", "isoCode": "GI"},
    {"name": "Greece", "dialCode": "+30", "isoCode": "GR"},
    {"name": "Greenland", "dialCode": "+299", "isoCode": "GL"},
    {"name": "Grenada", "dialCode": "+1473", "isoCode": "GD"},
    {"name": "Guadeloupe", "dialCode": "+590", "isoCode": "GP"},
    {"name": "Guam", "dialCode": "+1671", "isoCode": "GU"},
    {"name": "Guatemala", "dialCode": "+502", "isoCode": "GT"},
    {"name": "Guernsey", "dialCode": "+44", "isoCode": "GG"},
    {"name": "Guinea", "dialCode": "+224", "isoCode": "GN"},
    {"name": "Guinea-Bissau", "dialCode": "+245", "isoCode": "GW"},
    {"name": "Guyana", "dialCode": "+595", "isoCode": "GY"},
    {"name": "Haiti", "dialCode": "+509", "isoCode": "HT"},
    {
      "name": "Holy See (Vatican City State)",
      "dialCode": "+379",
      "isoCode": "VA"
    },
    {"name": "Honduras", "dialCode": "+504", "isoCode": "HN"},
    {"name": "Hong Kong", "dialCode": "+852", "isoCode": "HK"},
    {"name": "Hungary", "dialCode": "+36", "isoCode": "HU"},
    {"name": "Iceland", "dialCode": "+354", "isoCode": "IS"},
    {"name": "India", "dialCode": "+91", "isoCode": "IN"},
    {"name": "Indonesia", "dialCode": "+62", "isoCode": "ID"},
    {
      "name": "Iran, Islamic Republic of Persian Gulf",
      "dialCode": "+98",
      "isoCode": "IR"
    },
    {"name": "Iraq", "dialCode": "+964", "isoCode": "IQ"},
    {"name": "Ireland", "dialCode": "+353", "isoCode": "IE"},
    {"name": "Isle of Man", "dialCode": "+44", "isoCode": "IM"},
    {"name": "Israel", "dialCode": "+972", "isoCode": "IL"},
    {"name": "Italy", "dialCode": "+39", "isoCode": "IT"},
    {"name": "Jamaica", "dialCode": "+1876", "isoCode": "JM"},
    {"name": "Japan", "dialCode": "+81", "isoCode": "JP"},
    {"name": "Jersey", "dialCode": "+44", "isoCode": "JE"},
    {"name": "Jordan", "dialCode": "+962", "isoCode": "JO"},
    {"name": "Kazakhstan", "dialCode": "+77", "isoCode": "KZ"},
    {"name": "Kenya", "dialCode": "+254", "isoCode": "KE"},
    {"name": "Kiribati", "dialCode": "+686", "isoCode": "KI"},
    {
      "name": "Korea, Democratic People's Republic of Korea",
      "dialCode": "+850",
      "isoCode": "KP"
    },
    {
      "name": "Korea, Republic of South Korea",
      "dialCode": "+82",
      "isoCode": "KR"
    },
    {"name": "Kuwait", "dialCode": "+965", "isoCode": "KW"},
    {"name": "Kyrgyzstan", "dialCode": "+996", "isoCode": "KG"},
    {"name": "Laos", "dialCode": "+856", "isoCode": "LA"},
    {"name": "Latvia", "dialCode": "+371", "isoCode": "LV"},
    {"name": "Lebanon", "dialCode": "+961", "isoCode": "LB"},
    {"name": "Lesotho", "dialCode": "+266", "isoCode": "LS"},
    {"name": "Liberia", "dialCode": "+231", "isoCode": "LR"},
    {"name": "Libyan Arab Jamahiriya", "dialCode": "+218", "isoCode": "LY"},
    {"name": "Liechtenstein", "dialCode": "+423", "isoCode": "LI"},
    {"name": "Lithuania", "dialCode": "+370", "isoCode": "LT"},
    {"name": "Luxembourg", "dialCode": "+352", "isoCode": "LU"},
    {"name": "Macao", "dialCode": "+853", "isoCode": "MO"},
    {"name": "Macedonia", "dialCode": "+389", "isoCode": "MK"},
    {"name": "Madagascar", "dialCode": "+261", "isoCode": "MG"},
    {"name": "Malawi", "dialCode": "+265", "isoCode": "MW"},
    {"name": "Malaysia", "dialCode": "+60", "isoCode": "MY"},
    {"name": "Maldives", "dialCode": "+960", "isoCode": "MV"},
    {"name": "Mali", "dialCode": "+223", "isoCode": "ML"},
    {"name": "Malta", "dialCode": "+356", "isoCode": "MT"},
    {"name": "Marshall Islands", "dialCode": "+692", "isoCode": "MH"},
    {"name": "Martinique", "dialCode": "+596", "isoCode": "MQ"},
    {"name": "Mauritania", "dialCode": "+222", "isoCode": "MR"},
    {"name": "Mauritius", "dialCode": "+230", "isoCode": "MU"},
    {"name": "Mayotte", "dialCode": "+262", "isoCode": "YT"},
    {"name": "Mexico", "dialCode": "+52", "isoCode": "MX"},
    {
      "name": "Micronesia, Federated States of Micronesia",
      "dialCode": "+691",
      "isoCode": "FM"
    },
    {"name": "Moldova", "dialCode": "+373", "isoCode": "MD"},
    {"name": "Monaco", "dialCode": "+377", "isoCode": "MC"},
    {"name": "Mongolia", "dialCode": "+976", "isoCode": "MN"},
    {"name": "Montenegro", "dialCode": "+382", "isoCode": "ME"},
    {"name": "Montserrat", "dialCode": "+1664", "isoCode": "MS"},
    {"name": "Morocco", "dialCode": "+212", "isoCode": "MA"},
    {"name": "Mozambique", "dialCode": "+258", "isoCode": "MZ"},
    {"name": "Myanmar", "dialCode": "+95", "isoCode": "MM"},
    {"name": "Namibia", "dialCode": "+264", "isoCode": "NA"},
    {"name": "Nauru", "dialCode": "+674", "isoCode": "NR"},
    {"name": "Nepal", "dialCode": "+977", "isoCode": "NP"},
    {"name": "Netherlands", "dialCode": "+31", "isoCode": "NL"},
    {"name": "Netherlands Antilles", "dialCode": "+599", "isoCode": "AN"},
    {"name": "New Caledonia", "dialCode": "+687", "isoCode": "NC"},
    {"name": "New Zealand", "dialCode": "+64", "isoCode": "NZ"},
    {"name": "Nicaragua", "dialCode": "+505", "isoCode": "NI"},
    {"name": "Niger", "dialCode": "+227", "isoCode": "NE"},
    {"name": "Nigeria", "dialCode": "+234", "isoCode": "NG"},
    {"name": "Niue", "dialCode": "+683", "isoCode": "NU"},
    {"name": "Norfolk Island", "dialCode": "+672", "isoCode": "NF"},
    {"name": "Northern Mariana Islands", "dialCode": "+1670", "isoCode": "MP"},
    {"name": "Norway", "dialCode": "+47", "isoCode": "NO"},
    {"name": "Oman", "dialCode": "+968", "isoCode": "OM"},
    {"name": "Pakistan", "dialCode": "+92", "isoCode": "PK"},
    {"name": "Palau", "dialCode": "+680", "isoCode": "PW"},
    {
      "name": "Palestinian Territory, Occupied",
      "dialCode": "+970",
      "isoCode": "PS"
    },
    {"name": "Panama", "dialCode": "+507", "isoCode": "PA"},
    {"name": "Papua New Guinea", "dialCode": "+675", "isoCode": "PG"},
    {"name": "Paraguay", "dialCode": "+595", "isoCode": "PY"},
    {"name": "Peru", "dialCode": "+51", "isoCode": "PE"},
    {"name": "Philippines", "dialCode": "+63", "isoCode": "PH"},
    {"name": "Pitcairn", "dialCode": "+872", "isoCode": "PN"},
    {"name": "Poland", "dialCode": "+48", "isoCode": "PL"},
    {"name": "Portugal", "dialCode": "+351", "isoCode": "PT"},
    {"name": "Puerto Rico", "dialCode": "+1939", "isoCode": "PR"},
    {"name": "Qatar", "dialCode": "+974", "isoCode": "QA"},
    {"name": "Romania", "dialCode": "+40", "isoCode": "RO"},
    {"name": "Russia", "dialCode": "+7", "isoCode": "RU"},
    {"name": "Rwanda", "dialCode": "+250", "isoCode": "RW"},
    {"name": "Reunion", "dialCode": "+262", "isoCode": "RE"},
    {"name": "Saint Barthelemy", "dialCode": "+590", "isoCode": "BL"},
    {
      "name": "Saint Helena, Ascension and Tristan Da Cunha",
      "dialCode": "+290",
      "isoCode": "SH"
    },
    {"name": "Saint Kitts and Nevis", "dialCode": "+1869", "isoCode": "KN"},
    {"name": "Saint Lucia", "dialCode": "+1758", "isoCode": "LC"},
    {"name": "Saint Martin", "dialCode": "+590", "isoCode": "MF"},
    {"name": "Saint Pierre and Miquelon", "dialCode": "+508", "isoCode": "PM"},
    {
      "name": "Saint Vincent and the Grenadines",
      "dialCode": "+1784",
      "isoCode": "VC"
    },
    {"name": "Samoa", "dialCode": "+685", "isoCode": "WS"},
    {"name": "San Marino", "dialCode": "+378", "isoCode": "SM"},
    {"name": "Sao Tome and Principe", "dialCode": "+239", "isoCode": "ST"},
    {"name": "Saudi Arabia", "dialCode": "+966", "isoCode": "SA"},
    {"name": "Senegal", "dialCode": "+221", "isoCode": "SN"},
    {"name": "Serbia", "dialCode": "+381", "isoCode": "RS"},
    {"name": "Seychelles", "dialCode": "+248", "isoCode": "SC"},
    {"name": "Sierra Leone", "dialCode": "+232", "isoCode": "SL"},
    {"name": "Singapore", "dialCode": "+65", "isoCode": "SG"},
    {"name": "Slovakia", "dialCode": "+421", "isoCode": "SK"},
    {"name": "Slovenia", "dialCode": "+386", "isoCode": "SI"},
    {"name": "Solomon Islands", "dialCode": "+677", "isoCode": "SB"},
    {"name": "Somalia", "dialCode": "+252", "isoCode": "SO"},
    {"name": "South Africa", "dialCode": "+27", "isoCode": "ZA"},
    {"name": "South Sudan", "dialCode": "+211", "isoCode": "SS"},
    {
      "name": "South Georgia and the South Sandwich Islands",
      "dialCode": "+500",
      "isoCode": "GS"
    },
    {"name": "Spain", "dialCode": "+34", "isoCode": "ES"},
    {"name": "Sri Lanka", "dialCode": "+94", "isoCode": "LK"},
    {"name": "Sudan", "dialCode": "+249", "isoCode": "SD"},
    {"name": "Suriname", "dialCode": "+597", "isoCode": "SR"},
    {"name": "Svalbard and Jan Mayen", "dialCode": "+47", "isoCode": "SJ"},
    {"name": "Swaziland", "dialCode": "+268", "isoCode": "SZ"},
    {"name": "Sweden", "dialCode": "+46", "isoCode": "SE"},
    {"name": "Switzerland", "dialCode": "+41", "isoCode": "CH"},
    {"name": "Syrian Arab Republic", "dialCode": "+963", "isoCode": "SY"},
    {"name": "Taiwan", "dialCode": "+886", "isoCode": "TW"},
    {"name": "Tajikistan", "dialCode": "+992", "isoCode": "TJ"},
    {
      "name": "Tanzania, United Republic of Tanzania",
      "dialCode": "+255",
      "isoCode": "TZ"
    },
    {"name": "Thailand", "dialCode": "+66", "isoCode": "TH"},
    {"name": "Timor-Leste", "dialCode": "+670", "isoCode": "TL"},
    {"name": "Togo", "dialCode": "+228", "isoCode": "TG"},
    {"name": "Tokelau", "dialCode": "+690", "isoCode": "TK"},
    {"name": "Tonga", "dialCode": "+676", "isoCode": "TO"},
    {"name": "Trinidad and Tobago", "dialCode": "+1868", "isoCode": "TT"},
    {"name": "Tunisia", "dialCode": "+216", "isoCode": "TN"},
    {"name": "Turkey", "dialCode": "+90", "isoCode": "TR"},
    {"name": "Turkmenistan", "dialCode": "+993", "isoCode": "TM"},
    {"name": "Turks and Caicos Islands", "dialCode": "+1649", "isoCode": "TC"},
    {"name": "Tuvalu", "dialCode": "+688", "isoCode": "TV"},
    {"name": "Uganda", "dialCode": "+256", "isoCode": "UG"},
    {"name": "Ukraine", "dialCode": "+380", "isoCode": "UA"},
    {"name": "United Arab Emirates", "dialCode": "+971", "isoCode": "AE"},
    {"name": "United Kingdom", "dialCode": "+44", "isoCode": "GB"},
    {"name": "United States", "dialCode": "+1", "isoCode": "US"},
    {"name": "Uruguay", "dialCode": "+598", "isoCode": "UY"},
    {"name": "Uzbekistan", "dialCode": "+998", "isoCode": "UZ"},
    {"name": "Vanuatu", "dialCode": "+678", "isoCode": "VU"},
    {
      "name": "Venezuela, Bolivarian Republic of Venezuela",
      "dialCode": "+58",
      "isoCode": "VE"
    },
    {"name": "Vietnam", "dialCode": "+84", "isoCode": "VN"},
    {"name": "Virgin Islands, British", "dialCode": "+1284", "isoCode": "VG"},
    {"name": "Virgin Islands, U.S.", "dialCode": "+1340", "isoCode": "VI"},
    {"name": "Wallis and Futuna", "dialCode": "+681", "isoCode": "WF"},
    {"name": "Yemen", "dialCode": "+967", "isoCode": "YE"},
    {"name": "Zambia", "dialCode": "+260", "isoCode": "ZM"},
    {"name": "Zimbabwe", "dialCode": "+263", "isoCode": "ZW"}
  ].map((e) => Country.from(e)).toList();

  static List<Country> _tr = [
  {"name": "Afganistan", "dialCode": "+93", "isoCode": "AF"},
  {"name": "Arnavutluk", "dialCode": "+355", "isoCode": "AL"},
  {"name": "Cezayir", "dialCode": "+213", "isoCode": "DZ"},
  {"name": "Andorra", "dialCode": "+376", "isoCode": "AD"},
  {"name": "Angola", "dialCode": "+244", "isoCode": "AO"},
  {"name": "Antigua ve Barbuda", "dialCode": "+1", "isoCode": "AG"},
  {"name": "Arjantin", "dialCode": "+54", "isoCode": "AR"},
  {"name": "Ermenistan", "dialCode": "+374", "isoCode": "AM"},
  {"name": "Avustralya", "dialCode": "+61", "isoCode": "AU"},
  {"name": "Avusturya", "dialCode": "+43", "isoCode": "AT"},
  {"name": "Azerbaycan", "dialCode": "+994", "isoCode": "AZ"},
  {"name": "Bahamalar", "dialCode": "+1", "isoCode": "BS"},
  {"name": "Bahreyn", "dialCode": "+973", "isoCode": "BH"},
  {"name": "Bangladeş", "dialCode": "+880", "isoCode": "BD"},
  {"name": "Barbados", "dialCode": "+1", "isoCode": "BB"},
  {"name": "Belarus", "dialCode": "+375", "isoCode": "BY"},
  {"name": "Belçika", "dialCode": "+32", "isoCode": "BE"},
  {"name": "Belize", "dialCode": "+501", "isoCode": "BZ"},
  {"name": "Benin", "dialCode": "+229", "isoCode": "BJ"},
  {"name": "Bhutan", "dialCode": "+975", "isoCode": "BT"},
  {"name": "Bolivya", "dialCode": "+591", "isoCode": "BO"},
  {"name": "Bosna Hersek", "dialCode": "+387", "isoCode": "BA"},
  {"name": "Botsvana", "dialCode": "+267", "isoCode": "BW"},
  {"name": "Brezilya", "dialCode": "+55", "isoCode": "BR"},
  {"name": "Brunei", "dialCode": "+673", "isoCode": "BN"},
  {"name": "Bulgaristan", "dialCode": "+359", "isoCode": "BG"},
  {"name": "Burkina Faso", "dialCode": "+226", "isoCode": "BF"},
  {"name": "Burundi", "dialCode": "+257", "isoCode": "BI"},
  {"name": "Kamboçya", "dialCode": "+855", "isoCode": "KH"},
  {"name": "Kamerun", "dialCode": "+237", "isoCode": "CM"},
  {"name": "Kanada", "dialCode": "+1", "isoCode": "CA"},
  {"name": "Kap Verde", "dialCode": "+238", "isoCode": "CV"},
  {"name": "Orta Afrika Cumhuriyeti", "dialCode": "+236", "isoCode": "CF"},
  {"name": "Çad", "dialCode": "+235", "isoCode": "TD"},
  {"name": "Şili", "dialCode": "+56", "isoCode": "CL"},
  {"name": "Çin", "dialCode": "+86", "isoCode": "CN"},
  {"name": "Kolombiya", "dialCode": "+57", "isoCode": "CO"},
  {"name": "Komorlar", "dialCode": "+269", "isoCode": "KM"},
  {"name": "Kongo (Brazavil)", "dialCode": "+242", "isoCode": "CG"},
  {"name": "Kongo (Kinşasa)", "dialCode": "+243", "isoCode": "CD"},
  {"name": "Kosta Rika", "dialCode": "+506", "isoCode": "CR"},
  {"name": "Hırvatistan", "dialCode": "+385", "isoCode": "HR"},
  {"name": "Küba", "dialCode": "+53", "isoCode": "CU"},
  {"name": "Kıbrıs", "dialCode": "+357", "isoCode": "CY"},
  {"name": "Çek Cumhuriyeti", "dialCode": "+420", "isoCode": "CZ"},
  {"name": "Danimarka", "dialCode": "+45", "isoCode": "DK"},
  {"name": "Cibuti", "dialCode": "+253", "isoCode": "DJ"},
  {"name": "Dominika", "dialCode": "+1", "isoCode": "DM"},
  {"name": "Dominik Cumhuriyeti", "dialCode": "+1", "isoCode": "DO"},
  {"name": "Timor-Leste", "dialCode": "+670", "isoCode": "TL"},
  {"name": "Ekvador", "dialCode": "+593", "isoCode": "EC"},
  {"name": "Mısır", "dialCode": "+20", "isoCode": "EG"},
  {"name": "El Salvador", "dialCode": "+503", "isoCode": "SV"},
  {"name": "Ekvator Ginesi", "dialCode": "+240", "isoCode": "GQ"},
  {"name": "Eritre", "dialCode": "+291", "isoCode": "ER"},
  {"name": "Estonya", "dialCode": "+372", "isoCode": "EE"},
  {"name": "Etiyopya", "dialCode": "+251", "isoCode": "ET"},
  {"name": "Fiji", "dialCode": "+679", "isoCode": "FJ"},
  {"name": "Finlandiya", "dialCode": "+358", "isoCode": "FI"},
  {"name": "Fransa", "dialCode": "+33", "isoCode": "FR"},
  {"name": "Gabon", "dialCode": "+241", "isoCode": "GA"},
  {"name": "Gambia", "dialCode": "+220", "isoCode": "GM"},
  {"name": "Gürcistan", "dialCode": "+995", "isoCode": "GE"},
  {"name": "Almanya", "dialCode": "+49", "isoCode": "DE"},
  {"name": "Gana", "dialCode": "+233", "isoCode": "GH"},
  {"name": "Yunanistan", "dialCode": "+30", "isoCode": "GR"},
  {"name": "Grenada", "dialCode": "+1", "isoCode": "GD"},
  {"name": "Guatemala", "dialCode": "+502", "isoCode": "GT"},
  {"name": "Gine", "dialCode": "+224", "isoCode": "GN"},
  {"name": "Gine-Bissau", "dialCode": "+245", "isoCode": "GW"},
  {"name": "Guyana", "dialCode": "+592", "isoCode": "GY"},
  {"name": "Haiti", "dialCode": "+509", "isoCode": "HT"},
  {"name": "Honduras", "dialCode": "+504", "isoCode": "HN"},
  {"name": "Macaristan", "dialCode": "+36", "isoCode": "HU"},
  {"name": "İzlanda", "dialCode": "+354", "isoCode": "IS"},
  {"name": "Hindistan", "dialCode": "+91", "isoCode": "IN"},
  {"name": "Endonezya", "dialCode": "+62", "isoCode": "ID"},
  {"name": "İran", "dialCode": "+98", "isoCode": "IR"},
  {"name": "Irak", "dialCode": "+964", "isoCode": "IQ"},
  {"name": "İrlanda", "dialCode": "+353", "isoCode": "IE"},
  {"name": "İsrail", "dialCode": "+972", "isoCode": "IL"},
  {"name": "İtalya", "dialCode": "+39", "isoCode": "IT"},
  {"name": "Jamayka", "dialCode": "+1", "isoCode": "JM"},
  {"name": "Japonya", "dialCode": "+81", "isoCode": "JP"},
  {"name": "Ürdün", "dialCode": "+962", "isoCode": "JO"},
  {"name": "Kazakistan", "dialCode": "+7", "isoCode": "KZ"},
  {"name": "Kenya", "dialCode": "+254", "isoCode": "KE"},
  {"name": "Kiribati", "dialCode": "+686", "isoCode": "KI"},
  {"name": "Kuveyt", "dialCode": "+965", "isoCode": "KW"},
  {"name": "Kırgızistan", "dialCode": "+996", "isoCode": "KG"},
  {"name": "Laos", "dialCode": "+856", "isoCode": "LA"},
  {"name": "Letonya", "dialCode": "+371", "isoCode": "LV"},
  {"name": "Lübnan", "dialCode": "+961", "isoCode": "LB"},
  {"name": "Lesotho", "dialCode": "+266", "isoCode": "LS"},
  {"name": "Liberia", "dialCode": "+231", "isoCode": "LR"},
  {"name": "Libya", "dialCode": "+218", "isoCode": "LY"},
  {"name": "Liechtenstein", "dialCode": "+423", "isoCode": "LI"},
  {"name": "Litvanya", "dialCode": "+370", "isoCode": "LT"},
  {"name": "Lüksemburg", "dialCode": "+352", "isoCode": "LU"},
  {"name": "Makedonya", "dialCode": "+389", "isoCode": "MK"},
  {"name": "Madagaskar", "dialCode": "+261", "isoCode": "MG"},
  {"name": "Malavi", "dialCode": "+265", "isoCode": "MW"},
  {"name": "Malezya", "dialCode": "+60", "isoCode": "MY"},
  {"name": "Maldivler", "dialCode": "+960", "isoCode": "MV"},
  {"name": "Mali", "dialCode": "+223", "isoCode": "ML"},
  {"name": "Malta", "dialCode": "+356", "isoCode": "MT"},
  {"name": "Marshall Adaları", "dialCode": "+692", "isoCode": "MH"},
  {"name": "Moritanya", "dialCode": "+222", "isoCode": "MR"},
  {"name": "Mauritius", "dialCode": "+230", "isoCode": "MU"},
  {"name": "Meksika", "dialCode": "+52", "isoCode": "MX"},
  {"name": "Mikronezya", "dialCode": "+691", "isoCode": "FM"},
  {"name": "Moldova", "dialCode": "+373", "isoCode": "MD"},
  {"name": "Monako", "dialCode": "+377", "isoCode": "MC"},
  {"name": "Moğolistan", "dialCode": "+976", "isoCode": "MN"},
  {"name": "Karadağ", "dialCode": "+382", "isoCode": "ME"},
  {"name": "Fas", "dialCode": "+212", "isoCode": "MA"},
  {"name": "Mozambik", "dialCode": "+258", "isoCode": "MZ"},
  {"name": "Myanmar", "dialCode": "+95", "isoCode": "MM"},
  {"name": "Namibya", "dialCode": "+264", "isoCode": "nan"},
  {"name": "Nauru", "dialCode": "+674", "isoCode": "NR"},
  {"name": "Nepal", "dialCode": "+977", "isoCode": "NP"},
  {"name": "Hollanda", "dialCode": "+31", "isoCode": "NL"},
  {"name": "Yeni Zelanda", "dialCode": "+64", "isoCode": "NZ"},
  {"name": "Nikaragua", "dialCode": "+505", "isoCode": "NI"},
  {"name": "Nijer", "dialCode": "+227", "isoCode": "NE"},
  {"name": "Nijerya", "dialCode": "+234", "isoCode": "NG"},
  {"name": "Norveç", "dialCode": "+47", "isoCode": "NO"},
  {"name": "Umman", "dialCode": "+968", "isoCode": "OM"},
  {"name": "Pakistan", "dialCode": "+92", "isoCode": "PK"},
  {"name": "Palau", "dialCode": "+680", "isoCode": "PW"},
  {"name": "Panama", "dialCode": "+507", "isoCode": "PA"},
  {"name": "Papua Yeni Gine", "dialCode": "+675", "isoCode": "PG"},
  {"name": "Paraguay", "dialCode": "+595", "isoCode": "PY"},
  {"name": "Peru", "dialCode": "+51", "isoCode": "PE"},
  {"name": "Filipinler", "dialCode": "+63", "isoCode": "PH"},
  {"name": "Polonya", "dialCode": "+48", "isoCode": "PL"},
  {"name": "Portekiz", "dialCode": "+351", "isoCode": "PT"},
  {"name": "Katar", "dialCode": "+974", "isoCode": "QA"},
  {"name": "Romanya", "dialCode": "+40", "isoCode": "RO"},
  {"name": "Rusya", "dialCode": "+7", "isoCode": "RU"},
  {"name": "Ruanda", "dialCode": "+250", "isoCode": "RW"},
  {"name": "Saint Kitts ve Nevis", "dialCode": "+1", "isoCode": "KN"},
  {"name": "Saint Lucia", "dialCode": "+1", "isoCode": "LC"},
  {"name": "Saint Vincent ve Grenadinler", "dialCode": "+1", "isoCode": "VC"},
  {"name": "Samoa", "dialCode": "+685", "isoCode": "WS"},
  {"name": "San Marino", "dialCode": "+378", "isoCode": "SM"},
  {"name": "Sao Tome ve Principe", "dialCode": "+239", "isoCode": "ST"},
  {"name": "Suudi Arabistan", "dialCode": "+966", "isoCode": "SA"},
  {"name": "Senegal", "dialCode": "+221", "isoCode": "SN"},
  {"name": "Sırbistan", "dialCode": "+381", "isoCode": "RS"},
  {"name": "Seyşeller", "dialCode": "+248", "isoCode": "SC"},
  {"name": "Sierra Leone", "dialCode": "+232", "isoCode": "SL"},
  {"name": "Singapur", "dialCode": "+65", "isoCode": "SG"},
  {"name": "Slovakya", "dialCode": "+421", "isoCode": "SK"},
  {"name": "Slovenya", "dialCode": "+386", "isoCode": "SI"},
  {"name": "Solomon Adaları", "dialCode": "+677", "isoCode": "SB"},
  {"name": "Somali", "dialCode": "+252", "isoCode": "SO"},
  {"name": "Güney Afrika", "dialCode": "+27", "isoCode": "ZA"},
  {"name": "Güney Kore", "dialCode": "+82", "isoCode": "KR"},
  {"name": "İspanya", "dialCode": "+34", "isoCode": "ES"},
  {"name": "Sri Lanka", "dialCode": "+94", "isoCode": "LK"},
  {"name": "Sudan", "dialCode": "+249", "isoCode": "SD"},
  {"name": "Surinam", "dialCode": "+597", "isoCode": "SR"},
  {"name": "Swaziland", "dialCode": "+268", "isoCode": "SZ"},
  {"name": "İsveç", "dialCode": "+46", "isoCode": "SE"},
  {"name": "İsviçre", "dialCode": "+41", "isoCode": "CH"},
  {"name": "Suriye", "dialCode": "+963", "isoCode": "SY"},
  {"name": "Tacikistan", "dialCode": "+992", "isoCode": "TJ"},
  {"name": "Tanzanya", "dialCode": "+255", "isoCode": "TZ"},
  {"name": "Tayland", "dialCode": "+66", "isoCode": "TH"},
  {"name": "Togo", "dialCode": "+228", "isoCode": "TG"},
  {"name": "Tonga", "dialCode": "+676", "isoCode": "TO"},
  {"name": "Trinidad ve Tobago", "dialCode": "+1", "isoCode": "TT"},
  {"name": "Tunus", "dialCode": "+216", "isoCode": "TN"},
  {"name": "Türkiye", "dialCode": "+90", "isoCode": "TR"},
  {"name": "Türkmenistan", "dialCode": "+993", "isoCode": "TM"},
  {"name": "Tuvalu", "dialCode": "+688", "isoCode": "TV"},
  {"name": "Uganda", "dialCode": "+256", "isoCode": "UG"},
  {"name": "Ukrayna", "dialCode": "+380", "isoCode": "UA"},
  {"name": "Birleşik Arap Emirlikleri", "dialCode": "+971", "isoCode": "AE"},
  {"name": "Birleşik Krallık", "dialCode": "+44", "isoCode": "GB"},
  {"name": "Amerika Birleşik Devletleri", "dialCode": "+1", "isoCode": "US"},
  {"name": "Uruguay", "dialCode": "+598", "isoCode": "UY"},
  {"name": "Özbekistan", "dialCode": "+998", "isoCode": "UZ"},
  {"name": "Vanuatu", "dialCode": "+678", "isoCode": "VU"},
  {"name": "Vatikan", "dialCode": "+379", "isoCode": "VA"},
  {"name": "Venezuela", "dialCode": "+58", "isoCode": "VE"},
  {"name": "Vietnam", "dialCode": "+84", "isoCode": "VN"},
  {"name": "Yemen", "dialCode": "+967", "isoCode": "YE"},
  {"name": "Zambiya", "dialCode": "+260", "isoCode": "ZM"},
  {"name": "Zimbabve", "dialCode": "+263", "isoCode": "ZW"},
  ].map((e) => Country.from(e)).toList();
  static List<Country> _de = [
  {"name": "Afghanistan", "dialCode": "+93", "isoCode": "AF"},
  {"name": "Albanien", "dialCode": "+355", "isoCode": "AL"},
  {"name": "Algerien", "dialCode": "+213", "isoCode": "DZ"},
  {"name": "Andorra", "dialCode": "+376", "isoCode": "AD"},
  {"name": "Angola", "dialCode": "+244", "isoCode": "AO"},
  {"name": "Antigua und Barbuda", "dialCode": "+1", "isoCode": "AG"},
  {"name": "Argentinien", "dialCode": "+54", "isoCode": "AR"},
  {"name": "Armenien", "dialCode": "+374", "isoCode": "AM"},
  {"name": "Australien", "dialCode": "+61", "isoCode": "AU"},
  {"name": "Österreich", "dialCode": "+43", "isoCode": "AT"},
  {"name": "Aserbaidschan", "dialCode": "+994", "isoCode": "AZ"},
  {"name": "Bahamas", "dialCode": "+1", "isoCode": "BS"},
  {"name": "Bahrain", "dialCode": "+973", "isoCode": "BH"},
  {"name": "Bangladesch", "dialCode": "+880", "isoCode": "BD"},
  {"name": "Barbados", "dialCode": "+1", "isoCode": "BB"},
  {"name": "Belarus", "dialCode": "+375", "isoCode": "BY"},
  {"name": "Belgien", "dialCode": "+32", "isoCode": "BE"},
  {"name": "Belize", "dialCode": "+501", "isoCode": "BZ"},
  {"name": "Benin", "dialCode": "+229", "isoCode": "BJ"},
  {"name": "Bhutan", "dialCode": "+975", "isoCode": "BT"},
  {"name": "Bolivien", "dialCode": "+591", "isoCode": "BO"},
  {"name": "Bosnien und Herzegowina", "dialCode": "+387", "isoCode": "BA"},
  {"name": "Botswana", "dialCode": "+267", "isoCode": "BW"},
  {"name": "Brasilien", "dialCode": "+55", "isoCode": "BR"},
  {"name": "Brunei", "dialCode": "+673", "isoCode": "BN"},
  {"name": "Bulgarien", "dialCode": "+359", "isoCode": "BG"},
  {"name": "Burkina Faso", "dialCode": "+226", "isoCode": "BF"},
  {"name": "Burundi", "dialCode": "+257", "isoCode": "BI"},
  {"name": "Kambodscha", "dialCode": "+855", "isoCode": "KH"},
  {"name": "Kamerun", "dialCode": "+237", "isoCode": "CM"},
  {"name": "Kanada", "dialCode": "+1", "isoCode": "CA"},
  {"name": "Kap Verde", "dialCode": "+238", "isoCode": "CV"},
  {"name": "Zentralafrikanische Republik", "dialCode": "+236", "isoCode": "CF"},
  {"name": "Tschad", "dialCode": "+235", "isoCode": "TD"},
  {"name": "Chile", "dialCode": "+56", "isoCode": "CL"},
  {"name": "China", "dialCode": "+86", "isoCode": "CN"},
  {"name": "Kolumbien", "dialCode": "+57", "isoCode": "CO"},
  {"name": "Komoren", "dialCode": "+269", "isoCode": "KM"},
  {"name": "Kongo (Brazzaville)", "dialCode": "+242", "isoCode": "CG"},
  {"name": "Kongo (Kinshasa)", "dialCode": "+243", "isoCode": "CD"},
  {"name": "Costa Rica", "dialCode": "+506", "isoCode": "CR"},
  {"name": "Kroatien", "dialCode": "+385", "isoCode": "HR"},
  {"name": "Kuba", "dialCode": "+53", "isoCode": "CU"},
  {"name": "Zypern", "dialCode": "+357", "isoCode": "CY"},
  {"name": "Tschechische Republik", "dialCode": "+420", "isoCode": "CZ"},
  {"name": "Dänemark", "dialCode": "+45", "isoCode": "DK"},
  {"name": "Dschibuti", "dialCode": "+253", "isoCode": "DJ"},
  {"name": "Dominica", "dialCode": "+1", "isoCode": "DM"},
  {"name": "Dominikanische Republik", "dialCode": "+1", "isoCode": "DO"},
  {"name": "Osttimor", "dialCode": "+670", "isoCode": "TL"},
  {"name": "Ecuador", "dialCode": "+593", "isoCode": "EC"},
  {"name": "Ägypten", "dialCode": "+20", "isoCode": "EG"},
  {"name": "El Salvador", "dialCode": "+503", "isoCode": "SV"},
  {"name": "Äquatorialguinea", "dialCode": "+240", "isoCode": "GQ"},
  {"name": "Eritrea", "dialCode": "+291", "isoCode": "ER"},
  {"name": "Estland", "dialCode": "+372", "isoCode": "EE"},
  {"name": "Äthiopien", "dialCode": "+251", "isoCode": "ET"},
  {"name": "Fidschi", "dialCode": "+679", "isoCode": "FJ"},
  {"name": "Finnland", "dialCode": "+358", "isoCode": "FI"},
  {"name": "Frankreich", "dialCode": "+33", "isoCode": "FR"},
  {"name": "Gabun", "dialCode": "+241", "isoCode": "GA"},
  {"name": "Gambia", "dialCode": "+220", "isoCode": "GM"},
  {"name": "Georgien", "dialCode": "+995", "isoCode": "GE"},
  {"name": "Deutschland", "dialCode": "+49", "isoCode": "DE"},
  {"name": "Ghana", "dialCode": "+233", "isoCode": "GH"},
  {"name": "Griechenland", "dialCode": "+30", "isoCode": "GR"},
  {"name": "Grenada", "dialCode": "+1", "isoCode": "GD"},
  {"name": "Guatemala", "dialCode": "+502", "isoCode": "GT"},
  {"name": "Guinea", "dialCode": "+224", "isoCode": "GN"},
  {"name": "Guinea-Bissau", "dialCode": "+245", "isoCode": "GW"},
  {"name": "Guyana", "dialCode": "+592", "isoCode": "GY"},
  {"name": "Haiti", "dialCode": "+509", "isoCode": "HT"},
  {"name": "Honduras", "dialCode": "+504", "isoCode": "HN"},
  {"name": "Ungarn", "dialCode": "+36", "isoCode": "HU"},
  {"name": "Island", "dialCode": "+354", "isoCode": "IS"},
  {"name": "Indien", "dialCode": "+91", "isoCode": "IN"},
  {"name": "Indonesien", "dialCode": "+62", "isoCode": "ID"},
  {"name": "Iran", "dialCode": "+98", "isoCode": "IR"},
  {"name": "Irak", "dialCode": "+964", "isoCode": "IQ"},
  {"name": "Irland", "dialCode": "+353", "isoCode": "IE"},
  {"name": "Israel", "dialCode": "+972", "isoCode": "IL"},
  {"name": "Italien", "dialCode": "+39", "isoCode": "IT"},
  {"name": "Jamaika", "dialCode": "+1", "isoCode": "JM"},
  {"name": "Japan", "dialCode": "+81", "isoCode": "JP"},
  {"name": "Jordanien", "dialCode": "+962", "isoCode": "JO"},
  {"name": "Kasachstan", "dialCode": "+7", "isoCode": "KZ"},
  {"name": "Kenia", "dialCode": "+254", "isoCode": "KE"},
  {"name": "Kiribati", "dialCode": "+686", "isoCode": "KI"},
  {"name": "Kuwait", "dialCode": "+965", "isoCode": "KW"},
  {"name": "Kirgisistan", "dialCode": "+996", "isoCode": "KG"},
  {"name": "Laos", "dialCode": "+856", "isoCode": "LA"},
  {"name": "Lettland", "dialCode": "+371", "isoCode": "LV"},
  {"name": "Libanon", "dialCode": "+961", "isoCode": "LB"},
  {"name": "Lesotho", "dialCode": "+266", "isoCode": "LS"},
  {"name": "Liberia", "dialCode": "+231", "isoCode": "LR"},
  {"name": "Lybiens", "dialCode": "+218", "isoCode": "LY"},
  {"name": "Liechtenstein", "dialCode": "+423", "isoCode": "LI"},
  {"name": "Litauen", "dialCode": "+370", "isoCode": "LT"},
  {"name": "Luxemburg", "dialCode": "+352", "isoCode": "LU"},
  {"name": "Mazedonien", "dialCode": "+389", "isoCode": "MK"},
  {"name": "Madagaskar", "dialCode": "+261", "isoCode": "MG"},
  {"name": "Malawi", "dialCode": "+265", "isoCode": "MW"},
  {"name": "Malaysia", "dialCode": "+60", "isoCode": "MY"},
  {"name": "Malediven", "dialCode": "+960", "isoCode": "MV"},
  {"name": "Mali", "dialCode": "+223", "isoCode": "ML"},
  {"name": "Malta", "dialCode": "+356", "isoCode": "MT"},
  {"name": "Marshallinseln", "dialCode": "+692", "isoCode": "MH"},
  {"name": "Mauretanien", "dialCode": "+222", "isoCode": "MR"},
  {"name": "Mauritius", "dialCode": "+230", "isoCode": "MU"},
  {"name": "Mexiko", "dialCode": "+52", "isoCode": "MX"},
  {"name": "Mikronesien", "dialCode": "+691", "isoCode": "FM"},
  {"name": "Moldawien", "dialCode": "+373", "isoCode": "MD"},
  {"name": "Monaco", "dialCode": "+377", "isoCode": "MC"},
  {"name": "Mongolei", "dialCode": "+976", "isoCode": "MN"},
  {"name": "Montenegro", "dialCode": "+382", "isoCode": "ME"},
  {"name": "Marokko", "dialCode": "+212", "isoCode": "MA"},
  {"name": "Mosambik", "dialCode": "+258", "isoCode": "MZ"},
  {"name": "Myanmar", "dialCode": "+95", "isoCode": "MM"},
  {"name": "Namibia", "dialCode": "+264", "isoCode": "nan"},
  {"name": "Nauru", "dialCode": "+674", "isoCode": "NR"},
  {"name": "Nepal", "dialCode": "+977", "isoCode": "NP"},
  {"name": "Niederlande", "dialCode": "+31", "isoCode": "NL"},
  {"name": "Neuseeland", "dialCode": "+64", "isoCode": "NZ"},
  {"name": "Nicaragua", "dialCode": "+505", "isoCode": "NI"},
  {"name": "Niger", "dialCode": "+227", "isoCode": "NE"},
  {"name": "Nigeria", "dialCode": "+234", "isoCode": "NG"},
  {"name": "Norwegen", "dialCode": "+47", "isoCode": "NO"},
  {"name": "Oman", "dialCode": "+968", "isoCode": "OM"},
  {"name": "Pakistan", "dialCode": "+92", "isoCode": "PK"},
  {"name": "Palau", "dialCode": "+680", "isoCode": "PW"},
  {"name": "Panama", "dialCode": "+507", "isoCode": "PA"},
  {"name": "Papua-Neuguinea", "dialCode": "+675", "isoCode": "PG"},
  {"name": "Paraguay", "dialCode": "+595", "isoCode": "PY"},
  {"name": "Peru", "dialCode": "+51", "isoCode": "PE"},
  {"name": "Philippinen", "dialCode": "+63", "isoCode": "PH"},
  {"name": "Polen", "dialCode": "+48", "isoCode": "PL"},
  {"name": "Portugal", "dialCode": "+351", "isoCode": "PT"},
  {"name": "Katar", "dialCode": "+974", "isoCode": "QA"},
  {"name": "Rumänien", "dialCode": "+40", "isoCode": "RO"},
  {"name": "Russland", "dialCode": "+7", "isoCode": "RU"},
  {"name": "Ruanda", "dialCode": "+250", "isoCode": "RW"},
  {"name": "Saint Kitts und Nevis", "dialCode": "+1", "isoCode": "KN"},
  {"name": "Saint Lucia", "dialCode": "+1", "isoCode": "LC"},
  {"name": "Saint Vincent und die Grenadinen", "dialCode": "+1", "isoCode": "VC"},
  {"name": "Samoa", "dialCode": "+685", "isoCode": "WS"},
  {"name": "San Marino", "dialCode": "+378", "isoCode": "SM"},
  {"name": "São Tomé und Príncipe", "dialCode": "+239", "isoCode": "ST"},
  {"name": "Saudi-Arabien", "dialCode": "+966", "isoCode": "SA"},
  {"name": "Senegal", "dialCode": "+221", "isoCode": "SN"},
  {"name": "Serbien", "dialCode": "+381", "isoCode": "RS"},
  {"name": "Seychellen", "dialCode": "+248", "isoCode": "SC"},
  {"name": "Sierra Leone", "dialCode": "+232", "isoCode": "SL"},
  {"name": "Singapur", "dialCode": "+65", "isoCode": "SG"},
  {"name": "Slowakei", "dialCode": "+421", "isoCode": "SK"},
  {"name": "Slowenien", "dialCode": "+386", "isoCode": "SI"},
  {"name": "Solomon-Inseln", "dialCode": "+677", "isoCode": "SB"},
  {"name": "Somalia", "dialCode": "+252", "isoCode": "SO"},
  {"name": "Südafrika", "dialCode": "+27", "isoCode": "ZA"},
  {"name": "Großbritannien", "dialCode": "+82", "isoCode": "KR"},
  {"name": "Spanien", "dialCode": "+34", "isoCode": "ES"},
  {"name": "Sri Lanka", "dialCode": "+94", "isoCode": "LK"},
  {"name": "Sudan", "dialCode": "+249", "isoCode": "SD"},
  {"name": "Suriname", "dialCode": "+597", "isoCode": "SR"},
  {"name": "Swasiland", "dialCode": "+268", "isoCode": "SZ"},
  {"name": "Schweden", "dialCode": "+46", "isoCode": "SE"},
  {"name": "Schweiz", "dialCode": "+41", "isoCode": "CH"},
  {"name": "Syrien", "dialCode": "+963", "isoCode": "SY"},
  {"name": "Tadschikistan", "dialCode": "+992", "isoCode": "TJ"},
  {"name": "Tansania", "dialCode": "+255", "isoCode": "TZ"},
  {"name": "Thailand", "dialCode": "+66", "isoCode": "TH"},
  {"name": "Togo", "dialCode": "+228", "isoCode": "TG"},
  {"name": "Tonga", "dialCode": "+676", "isoCode": "TO"},
  {"name": "Trinidad und Tobago", "dialCode": "+1", "isoCode": "TT"},
  {"name": "Tunesien", "dialCode": "+216", "isoCode": "TN"},
  {"name": "Türkei", "dialCode": "+90", "isoCode": "TR"},
  {"name": "Turkmenistan", "dialCode": "+993", "isoCode": "TM"},
  {"name": "Tuvalu", "dialCode": "+688", "isoCode": "TV"},
  {"name": "Uganda", "dialCode": "+256", "isoCode": "UG"},
  {"name": "Ukraine", "dialCode": "+380", "isoCode": "UA"},
  {"name": "Vereinigte Arabische Emirate", "dialCode": "+971", "isoCode": "AE"},
  {"name": "Vereinigtes Königreich", "dialCode": "+44", "isoCode": "GB"},
  {"name": "Vereinigte Staaten von Amerika", "dialCode": "+1", "isoCode": "US"},
  {"name": "Uruguay", "dialCode": "+598", "isoCode": "UY"},
  {"name": "Usbekistan", "dialCode": "+998", "isoCode": "UZ"},
  {"name": "Vanuatu", "dialCode": "+678", "isoCode": "VU"},
  {"name": "Vatikanstadt", "dialCode": "+379", "isoCode": "VA"},
  {"name": "Venezuela", "dialCode": "+58", "isoCode": "VE"},
  {"name": "Vietnam", "dialCode": "+84", "isoCode": "VN"},
  {"name": "Jemen", "dialCode": "+967", "isoCode": "YE"},
  {"name": "Sambia", "dialCode": "+260", "isoCode": "ZM"},
  {"name": "Simbabwe", "dialCode": "+263", "isoCode": "ZW"},
  ].map((e) => Country.from(e)).toList();
  static List<Country> _hi = [
  {"name": "अफ़ग़ानिस्तान", "dialCode": "+93", "isoCode": "AF"},
  {"name": "अल्बानिया", "dialCode": "+355", "isoCode": "AL"},
  {"name": "अल्जीरिया", "dialCode": "+213", "isoCode": "DZ"},
  {"name": "अंडोरा", "dialCode": "+376", "isoCode": "AD"},
  {"name": "अंगोला", "dialCode": "+244", "isoCode": "AO"},
  {"name": "एंटीगुआ और बारबुडा", "dialCode": "+1", "isoCode": "AG"},
  {"name": "अर्जेंटीना", "dialCode": "+54", "isoCode": "AR"},
  {"name": "आर्मीनिया", "dialCode": "+374", "isoCode": "AM"},
  {"name": "ऑस्ट्रेलिया", "dialCode": "+61", "isoCode": "AU"},
  {"name": "ऑस्ट्रिया", "dialCode": "+43", "isoCode": "AT"},
  {"name": "अज़रबैजान", "dialCode": "+994", "isoCode": "AZ"},
  {"name": "बहामास", "dialCode": "+1", "isoCode": "BS"},
  {"name": "बहरीन", "dialCode": "+973", "isoCode": "BH"},
  {"name": "बांग्लादेश", "dialCode": "+880", "isoCode": "BD"},
  {"name": "बारबाडोस", "dialCode": "+1", "isoCode": "BB"},
  {"name": "बेलारूस", "dialCode": "+375", "isoCode": "BY"},
  {"name": "बेल्जियम", "dialCode": "+32", "isoCode": "BE"},
  {"name": "बेलीज", "dialCode": "+501", "isoCode": "BZ"},
  {"name": "बेनिन", "dialCode": "+229", "isoCode": "BJ"},
  {"name": "भूटान", "dialCode": "+975", "isoCode": "BT"},
  {"name": "बोलीविया", "dialCode": "+591", "isoCode": "BO"},
  {"name": "बोस्निया और हर्ज़ेगोविना", "dialCode": "+387", "isoCode": "BA"},
  {"name": "बोत्सवाना", "dialCode": "+267", "isoCode": "BW"},
  {"name": "ब्राज़िल", "dialCode": "+55", "isoCode": "BR"},
  {"name": "ब्रुनेई", "dialCode": "+673", "isoCode": "BN"},
  {"name": "बुल्गारिया", "dialCode": "+359", "isoCode": "BG"},
  {"name": "बुर्किना फ़ासो", "dialCode": "+226", "isoCode": "BF"},
  {"name": "बुरुंडी", "dialCode": "+257", "isoCode": "BI"},
  {"name": "कंबोडिया", "dialCode": "+855", "isoCode": "KH"},
  {"name": "कैमरून", "dialCode": "+237", "isoCode": "CM"},
  {"name": "कनाडा", "dialCode": "+1", "isoCode": "CA"},
  {"name": "केप वर्दे", "dialCode": "+238", "isoCode": "CV"},
  {"name": "केंद्रीय अफ़्रीकी गणराज्य", "dialCode": "+236", "isoCode": "CF"},
  {"name": "चाड", "dialCode": "+235", "isoCode": "TD"},
  {"name": "चिली", "dialCode": "+56", "isoCode": "CL"},
  {"name": "चीन", "dialCode": "+86", "isoCode": "CN"},
  {"name": "कोलंबिया", "dialCode": "+57", "isoCode": "CO"},
  {"name": "कोमोरोस", "dialCode": "+269", "isoCode": "KM"},
  {"name": "कांगो (ब्राज़ाविल)", "dialCode": "+242", "isoCode": "CG"},
  {"name": "कांगो (किंशासा)", "dialCode": "+243", "isoCode": "CD"},
  {"name": "कोस्टा रिका", "dialCode": "+506", "isoCode": "CR"},
  {"name": "क्रोएशिया", "dialCode": "+385", "isoCode": "HR"},
  {"name": "क्यूबा", "dialCode": "+53", "isoCode": "CU"},
  {"name": "साइप्रस", "dialCode": "+357", "isoCode": "CY"},
  {"name": "चेक गणराज्य", "dialCode": "+420", "isoCode": "CZ"},
  {"name": "डेनमार्क", "dialCode": "+45", "isoCode": "DK"},
  {"name": "जिबूती", "dialCode": "+253", "isoCode": "DJ"},
  {"name": "डोमिनिका", "dialCode": "+1", "isoCode": "DM"},
  {"name": "डोमिनिकन गणराज्य", "dialCode": "+1", "isoCode": "DO"},
  {"name": "पूर्वी तिमोर", "dialCode": "+670", "isoCode": "TL"},
  {"name": "इक्वाडोर", "dialCode": "+593", "isoCode": "EC"},
  {"name": "मिस्र", "dialCode": "+20", "isoCode": "EG"},
  {"name": "अल सल्वाडोर", "dialCode": "+503", "isoCode": "SV"},
  {"name": "इक्वेटोरियल गिनी", "dialCode": "+240", "isoCode": "GQ"},
  {"name": "इरिट्रिया", "dialCode": "+291", "isoCode": "ER"},
  {"name": "एस्टोनिया", "dialCode": "+372", "isoCode": "EE"},
  {"name": "इथियोपिया", "dialCode": "+251", "isoCode": "ET"},
  {"name": "फ़िजी", "dialCode": "+679", "isoCode": "FJ"},
  {"name": "फ़िनलैंड", "dialCode": "+358", "isoCode": "FI"},
  {"name": "फ़्रांस", "dialCode": "+33", "isoCode": "FR"},
  {"name": "गैबन", "dialCode": "+241", "isoCode": "GA"},
  {"name": "गाम्बिया", "dialCode": "+220", "isoCode": "GM"},
  {"name": "जॉर्जिया", "dialCode": "+995", "isoCode": "GE"},
  {"name": "जर्मनी", "dialCode": "+49", "isoCode": "DE"},
  {"name": "घाना", "dialCode": "+233", "isoCode": "GH"},
  {"name": "ग्रीस", "dialCode": "+30", "isoCode": "GR"},
  {"name": "ग्रेनाडा", "dialCode": "+1", "isoCode": "GD"},
  {"name": "ग्वाटेमाला", "dialCode": "+502", "isoCode": "GT"},
  {"name": "गिनी", "dialCode": "+224", "isoCode": "GN"},
  {"name": "गिनी-बिसाऊ", "dialCode": "+245", "isoCode": "GW"},
  {"name": "गुयाना", "dialCode": "+592", "isoCode": "GY"},
  {"name": "हाइती", "dialCode": "+509", "isoCode": "HT"},
  {"name": "होंडुरास", "dialCode": "+504", "isoCode": "HN"},
  {"name": "हंगरी", "dialCode": "+36", "isoCode": "HU"},
  {"name": "आइसलैंड", "dialCode": "+354", "isoCode": "IS"},
  {"name": "भारत", "dialCode": "+91", "isoCode": "IN"},
  {"name": "इंडोनेशिया", "dialCode": "+62", "isoCode": "ID"},
  {"name": "ईरान", "dialCode": "+98", "isoCode": "IR"},
  {"name": "इराक", "dialCode": "+964", "isoCode": "IQ"},
  {"name": "आयरलैंड", "dialCode": "+353", "isoCode": "IE"},
  {"name": "इज़राइल", "dialCode": "+972", "isoCode": "IL"},
  {"name": "इटली", "dialCode": "+39", "isoCode": "IT"},
  {"name": "जमैका", "dialCode": "+1", "isoCode": "JM"},
  {"name": "जापान", "dialCode": "+81", "isoCode": "JP"},
  {"name": "जॉर्डन", "dialCode": "+962", "isoCode": "JO"},
  {"name": "कज़ाखस्तान", "dialCode": "+7", "isoCode": "KZ"},
  {"name": "केन्या", "dialCode": "+254", "isoCode": "KE"},
  {"name": "किरिबाती", "dialCode": "+686", "isoCode": "KI"},
  {"name": "कुवैत", "dialCode": "+965", "isoCode": "KW"},
  {"name": "किर्गिज़स्तान", "dialCode": "+996", "isoCode": "KG"},
  {"name": "लाओस", "dialCode": "+856", "isoCode": "LA"},
  {"name": "लातविया", "dialCode": "+371", "isoCode": "LV"},
  {"name": "लेबनान", "dialCode": "+961", "isoCode": "LB"},
  {"name": "लेसोथो", "dialCode": "+266", "isoCode": "LS"},
  {"name": "लाइबेरिया", "dialCode": "+231", "isoCode": "LR"},
  {"name": "लीबिया", "dialCode": "+218", "isoCode": "LY"},
  {"name": "लिक्टेनस्टीन", "dialCode": "+423", "isoCode": "LI"},
  {"name": "लिथुआनिया", "dialCode": "+370", "isoCode": "LT"},
  {"name": "लक्समबर्ग", "dialCode": "+352", "isoCode": "LU"},
  {"name": "मैसेडोनिया", "dialCode": "+389", "isoCode": "MK"},
  {"name": "मेडागास्कर", "dialCode": "+261", "isoCode": "MG"},
  {"name": "मलावी", "dialCode": "+265", "isoCode": "MW"},
  {"name": "मलेशिया", "dialCode": "+60", "isoCode": "MY"},
  {"name": "मालदीव", "dialCode": "+960", "isoCode": "MV"},
  {"name": "माली", "dialCode": "+223", "isoCode": "ML"},
  {"name": "माल्टा", "dialCode": "+356", "isoCode": "MT"},
  {"name": "मार्शल द्वीप", "dialCode": "+692", "isoCode": "MH"},
  {"name": "मॉरिटानिया", "dialCode": "+222", "isoCode": "MR"},
  {"name": "मॉरीशस", "dialCode": "+230", "isoCode": "MU"},
  {"name": "मेक्सिको", "dialCode": "+52", "isoCode": "MX"},
  {"name": "माइक्रोनेशिया", "dialCode": "+691", "isoCode": "FM"},
  {"name": "मॉल्डोवा", "dialCode": "+373", "isoCode": "MD"},
  {"name": "मोनाको", "dialCode": "+377", "isoCode": "MC"},
  {"name": "मंगोलिया", "dialCode": "+976", "isoCode": "MN"},
  {"name": "मोंटेनीग्रो", "dialCode": "+382", "isoCode": "ME"},
  {"name": "मोरक्को", "dialCode": "+212", "isoCode": "MA"},
  {"name": "मोज़ाम्बिक", "dialCode": "+258", "isoCode": "MZ"},
  {"name": "म्यांमार (बर्मा)", "dialCode": "+95", "isoCode": "MM"},
  {"name": "नामीबिया", "dialCode": "+264", "isoCode": "nan"},
  {"name": "नाउरु", "dialCode": "+674", "isoCode": "NR"},
  {"name": "नेपाल", "dialCode": "+977", "isoCode": "NP"},
  {"name": "नीदरलैंड", "dialCode": "+31", "isoCode": "NL"},
  {"name": "न्यूज़ीलैंड", "dialCode": "+64", "isoCode": "NZ"},
  {"name": "निकारागुआ", "dialCode": "+505", "isoCode": "NI"},
  {"name": "नाइजर", "dialCode": "+227", "isoCode": "NE"},
  {"name": "नाइजीरिया", "dialCode": "+234", "isoCode": "NG"},
  {"name": "नॉर्वे", "dialCode": "+47", "isoCode": "NO"},
  {"name": "ओमान", "dialCode": "+968", "isoCode": "OM"},
  {"name": "पाकिस्तान", "dialCode": "+92", "isoCode": "PK"},
  {"name": "पलाऊ", "dialCode": "+680", "isoCode": "PW"},
  {"name": "पनामा", "dialCode": "+507", "isoCode": "PA"},
  {"name": "पापुआ न्यू गिनी", "dialCode": "+675", "isoCode": "PG"},
  {"name": "पारागुए", "dialCode": "+595", "isoCode": "PY"},
  {"name": "पेरू", "dialCode": "+51", "isoCode": "PE"},
  {"name": "फिलीपींस", "dialCode": "+63", "isoCode": "PH"},
  {"name": "पोलैंड", "dialCode": "+48", "isoCode": "PL"},
  {"name": "पुर्तगाल", "dialCode": "+351", "isoCode": "PT"},
  {"name": "कतर", "dialCode": "+974", "isoCode": "QA"},
  {"name": "रोमानिया", "dialCode": "+40", "isoCode": "RO"},
  {"name": "रूस", "dialCode": "+7", "isoCode": "RU"},
  {"name": "रवांडा", "dialCode": "+250", "isoCode": "RW"},
  {"name": "सेंट किट्स और नेविस", "dialCode": "+1", "isoCode": "KN"},
  {"name": "सेंट लूसिया", "dialCode": "+1", "isoCode": "LC"},
  {"name": "सेंट विंसेंट और ग्रेनाडाइन्स", "dialCode": "+1", "isoCode": "VC"},
  {"name": "समोआ", "dialCode": "+685", "isoCode": "WS"},
  {"name": "सैन मारिनो", "dialCode": "+378", "isoCode": "SM"},
  {"name": "साओ टोम और प्रिंसिपे", "dialCode": "+239", "isoCode": "ST"},
  {"name": "सउदी अरब", "dialCode": "+966", "isoCode": "SA"},
  {"name": "सेनेगल", "dialCode": "+221", "isoCode": "SN"},
  {"name": "सर्बिया", "dialCode": "+381", "isoCode": "RS"},
  {"name": "सेशेल्स", "dialCode": "+248", "isoCode": "SC"},
  {"name": "सिएरा लेओन", "dialCode": "+232", "isoCode": "SL"},
  {"name": "सिंगापुर", "dialCode": "+65", "isoCode": "SG"},
  {"name": "स्लोवाकिया", "dialCode": "+421", "isoCode": "SK"},
  {"name": "स्लोवेनिया", "dialCode": "+386", "isoCode": "SI"},
  {"name": "सोलोमन द्वीपसमूह", "dialCode": "+677", "isoCode": "SB"},
  {"name": "सोमालिया", "dialCode": "+252", "isoCode": "SO"},
  {"name": "दक्षिण अफ्रीका", "dialCode": "+27", "isoCode": "ZA"},
  {"name": "दक्षिण कोरिया", "dialCode": "+82", "isoCode": "KR"},
  {"name": "स्पेन", "dialCode": "+34", "isoCode": "ES"},
  {"name": "श्रीलंका", "dialCode": "+94", "isoCode": "LK"},
  {"name": "सूडान", "dialCode": "+249", "isoCode": "SD"},
  {"name": "सुरिनाम", "dialCode": "+597", "isoCode": "SR"},
  {"name": "स्वाजीलैंड", "dialCode": "+268", "isoCode": "SZ"},
  {"name": "स्वीडन", "dialCode": "+46", "isoCode": "SE"},
  {"name": "स्विट्ज़रलैंड", "dialCode": "+41", "isoCode": "CH"},
  {"name": "सीरिया", "dialCode": "+963", "isoCode": "SY"},
  {"name": "ताज़िकिस्तान", "dialCode": "+992", "isoCode": "TJ"},
  {"name": "तंज़ानिया", "dialCode": "+255", "isoCode": "TZ"},
  {"name": "थाईलैंड", "dialCode": "+66", "isoCode": "TH"},
  {"name": "टोगो", "dialCode": "+228", "isoCode": "TG"},
  {"name": "टोंगा", "dialCode": "+676", "isoCode": "TO"},
  {"name": "त्रिनिडाद और टोबैगो", "dialCode": "+1", "isoCode": "TT"},
  {"name": "ट्यूनीशिया", "dialCode": "+216", "isoCode": "TN"},
  {"name": "तुर्की", "dialCode": "+90", "isoCode": "TR"},
  {"name": "तुर्कमेनिस्तान", "dialCode": "+993", "isoCode": "TM"},
  {"name": "तुवालू", "dialCode": "+688", "isoCode": "TV"},
  {"name": "युगांडा", "dialCode": "+256", "isoCode": "UG"},
  {"name": "यूक्रेन", "dialCode": "+380", "isoCode": "UA"},
  {"name": "संयुक्त अरब अमीरात", "dialCode": "+971", "isoCode": "AE"},
  {"name": "संयुक्त राज्य किंगडम", "dialCode": "+44", "isoCode": "GB"},
  {"name": "संयुक्त राज्य अमेरिका", "dialCode": "+1", "isoCode": "US"},
  {"name": "उरुग्वे", "dialCode": "+598", "isoCode": "UY"},
  {"name": "उज़्बेकिस्तान", "dialCode": "+998", "isoCode": "UZ"},
  {"name": "वानुआतू", "dialCode": "+678", "isoCode": "VU"},
  {"name": "वेटिकन सिटी", "dialCode": "+379", "isoCode": "VA"},
  {"name": "वेनेज़ुएला", "dialCode": "+58", "isoCode": "VE"},
  {"name": "वियतनाम", "dialCode": "+84", "isoCode": "VN"},
  {"name": "यमन", "dialCode": "+967", "isoCode": "YE"},
  {"name": "ज़ाम्बिया", "dialCode": "+260", "isoCode": "ZM"},
  {"name": "ज़िम्बाब्वे", "dialCode": "+263", "isoCode": "ZW"},
  ].map((e) => Country.from(e)).toList();
  static List<Country> _es = [
  {"name": "Afganistán", "dialCode": "+93", "isoCode": "AF"},
  {"name": "Albania", "dialCode": "+355", "isoCode": "AL"},
  {"name": "Argelia", "dialCode": "+213", "isoCode": "DZ"},
  {"name": "Andorra", "dialCode": "+376", "isoCode": "AD"},
  {"name": "Angola", "dialCode": "+244", "isoCode": "AO"},
  {"name": "Antigua y Barbuda", "dialCode": "+1", "isoCode": "AG"},
  {"name": "Argentina", "dialCode": "+54", "isoCode": "AR"},
  {"name": "Armenia", "dialCode": "+374", "isoCode": "AM"},
  {"name": "Australia", "dialCode": "+61", "isoCode": "AU"},
  {"name": "Austria", "dialCode": "+43", "isoCode": "AT"},
  {"name": "Azerbaiyán", "dialCode": "+994", "isoCode": "AZ"},
  {"name": "Bahamas", "dialCode": "+1", "isoCode": "BS"},
  {"name": "Bahréin", "dialCode": "+973", "isoCode": "BH"},
  {"name": "Bangladés", "dialCode": "+880", "isoCode": "BD"},
  {"name": "Barbados", "dialCode": "+1", "isoCode": "BB"},
  {"name": "Bielorrusia", "dialCode": "+375", "isoCode": "BY"},
  {"name": "Bélgica", "dialCode": "+32", "isoCode": "BE"},
  {"name": "Belice", "dialCode": "+501", "isoCode": "BZ"},
  {"name": "Benín", "dialCode": "+229", "isoCode": "BJ"},
  {"name": "Bután", "dialCode": "+975", "isoCode": "BT"},
  {"name": "Bolivia", "dialCode": "+591", "isoCode": "BO"},
  {"name": "Bosnia y Herzegovina", "dialCode": "+387", "isoCode": "BA"},
  {"name": "Botsuana", "dialCode": "+267", "isoCode": "BW"},
  {"name": "Brasil", "dialCode": "+55", "isoCode": "BR"},
  {"name": "Brunei", "dialCode": "+673", "isoCode": "BN"},
  {"name": "Bulgaria", "dialCode": "+359", "isoCode": "BG"},
  {"name": "Burkina Faso", "dialCode": "+226", "isoCode": "BF"},
  {"name": "Burundi", "dialCode": "+257", "isoCode": "BI"},
  {"name": "Camboya", "dialCode": "+855", "isoCode": "KH"},
  {"name": "Camerún", "dialCode": "+237", "isoCode": "CM"},
  {"name": "Canadá", "dialCode": "+1", "isoCode": "CA"},
  {"name": "Cabo Verde", "dialCode": "+238", "isoCode": "CV"},
  {"name": "CAR", "dialCode": "+236", "isoCode": "CF"},
  {"name": "Chad", "dialCode": "+235", "isoCode": "TD"},
  {"name": "Chile", "dialCode": "+56", "isoCode": "CL"},
  {"name": "China", "dialCode": "+86", "isoCode": "CN"},
  {"name": "Colombia", "dialCode": "+57", "isoCode": "CO"},
  {"name": "Comoras", "dialCode": "+269", "isoCode": "KM"},
  {"name": "Congo (Brazzaville)", "dialCode": "+242", "isoCode": "CG"},
  {"name": "Congo (Kinshasa)", "dialCode": "+243", "isoCode": "CD"},
  {"name": "Costa Rica", "dialCode": "+506", "isoCode": "CR"},
  {"name": "Croacia", "dialCode": "+385", "isoCode": "HR"},
  {"name": "Cuba", "dialCode": "+53", "isoCode": "CU"},
  {"name": "Cyprus", "dialCode": "+357", "isoCode": "CY"},
  {"name": "República Checa", "dialCode": "+420", "isoCode": "CZ"},
  {"name": "Dinamarca", "dialCode": "+45", "isoCode": "DK"},
  {"name": "Yibuti", "dialCode": "+253", "isoCode": "DJ"},
  {"name": "Dominica", "dialCode": "+1", "isoCode": "DM"},
  {"name": "República Dominicana", "dialCode": "+1", "isoCode": "DO"},
  {"name": "Timor Oriental", "dialCode": "+670", "isoCode": "TL"},
  {"name": "Ecuador", "dialCode": "+593", "isoCode": "EC"},
  {"name": "Egipto", "dialCode": "+20", "isoCode": "EG"},
  {"name": "El Salvador", "dialCode": "+503", "isoCode": "SV"},
  {"name": "Guinea Ecuatorial", "dialCode": "+240", "isoCode": "GQ"},
  {"name": "Eritrea", "dialCode": "+291", "isoCode": "ER"},
  {"name": "Estonia", "dialCode": "+372", "isoCode": "EE"},
  {"name": "Etiopía", "dialCode": "+251", "isoCode": "ET"},
  {"name": "Fiyi", "dialCode": "+679", "isoCode": "FJ"},
  {"name": "Finlandia", "dialCode": "+358", "isoCode": "FI"},
  {"name": "Francia", "dialCode": "+33", "isoCode": "FR"},
  {"name": "Gabón", "dialCode": "+241", "isoCode": "GA"},
  {"name": "Gambia", "dialCode": "+220", "isoCode": "GM"},
  {"name": "Georgia", "dialCode": "+995", "isoCode": "GE"},
  {"name": "Alemania", "dialCode": "+49", "isoCode": "DE"},
  {"name": "Ghana", "dialCode": "+233", "isoCode": "GH"},
  {"name": "Grecia", "dialCode": "+30", "isoCode": "GR"},
  {"name": "Grenada", "dialCode": "+1", "isoCode": "GD"},
  {"name": "Guatemala", "dialCode": "+502", "isoCode": "GT"},
  {"name": "Guinea", "dialCode": "+224", "isoCode": "GN"},
  {"name": "Guinea-Bisáu", "dialCode": "+245", "isoCode": "GW"},
  {"name": "Guyana", "dialCode": "+592", "isoCode": "GY"},
  {"name": "Haití", "dialCode": "+509", "isoCode": "HT"},
  {"name": "Honduras", "dialCode": "+504", "isoCode": "HN"},
  {"name": "Hungría", "dialCode": "+36", "isoCode": "HU"},
  {"name": "Islandia", "dialCode": "+354", "isoCode": "IS"},
  {"name": "India", "dialCode": "+91", "isoCode": "IN"},
  {"name": "Indonesia", "dialCode": "+62", "isoCode": "ID"},
  {"name": "Irán", "dialCode": "+98", "isoCode": "IR"},
  {"name": "Iraq", "dialCode": "+964", "isoCode": "IQ"},
  {"name": "Irlanda", "dialCode": "+353", "isoCode": "IE"},
  {"name": "Israel", "dialCode": "+972", "isoCode": "IL"},
  {"name": "Italia", "dialCode": "+39", "isoCode": "IT"},
  {"name": "Jamaica", "dialCode": "+1", "isoCode": "JM"},
  {"name": "Japón", "dialCode": "+81", "isoCode": "JP"},
  {"name": "Jordania", "dialCode": "+962", "isoCode": "JO"},
  {"name": "Kazajistán", "dialCode": "+7", "isoCode": "KZ"},
  {"name": "Kenia", "dialCode": "+254", "isoCode": "KE"},
  {"name": "Kiribati", "dialCode": "+686", "isoCode": "KI"},
  {"name": "Kuwait", "dialCode": "+965", "isoCode": "KW"},
  {"name": "Kirguistán", "dialCode": "+996", "isoCode": "KG"},
  {"name": "Laos", "dialCode": "+856", "isoCode": "LA"},
  {"name": "Letonia", "dialCode": "+371", "isoCode": "LV"},
  {"name": "Líbano", "dialCode": "+961", "isoCode": "LB"},
  {"name": "Lesoto", "dialCode": "+266", "isoCode": "LS"},
  {"name": "Liberia", "dialCode": "+231", "isoCode": "LR"},
  {"name": "Libia", "dialCode": "+218", "isoCode": "LY"},
  {"name": "Liechtenstein", "dialCode": "+423", "isoCode": "LI"},
  {"name": "Lituania", "dialCode": "+370", "isoCode": "LT"},
  {"name": "Luxemburgo", "dialCode": "+352", "isoCode": "LU"},
  {"name": "Macedonia", "dialCode": "+389", "isoCode": "MK"},
  {"name": "Madagascar", "dialCode": "+261", "isoCode": "MG"},
  {"name": "Malaui", "dialCode": "+265", "isoCode": "MW"},
  {"name": "Malasia", "dialCode": "+60", "isoCode": "MY"},
  {"name": "Maldivas", "dialCode": "+960", "isoCode": "MV"},
  {"name": "Malí", "dialCode": "+223", "isoCode": "ML"},
  {"name": "Malta", "dialCode": "+356", "isoCode": "MT"},
  {"name": "Islas Marshall", "dialCode": "+692", "isoCode": "MH"},
  {"name": "Mauritania", "dialCode": "+222", "isoCode": "MR"},
  {"name": "Mauricio", "dialCode": "+230", "isoCode": "MU"},
  {"name": "México", "dialCode": "+52", "isoCode": "MX"},
  {"name": "Micronesia", "dialCode": "+691", "isoCode": "FM"},
  {"name": "Moldavia", "dialCode": "+373", "isoCode": "MD"},
  {"name": "Mónaco", "dialCode": "+377", "isoCode": "MC"},
  {"name": "Mongolia", "dialCode": "+976", "isoCode": "MN"},
  {"name": "Montenegro", "dialCode": "+382", "isoCode": "ME"},
  {"name": "Marruecos", "dialCode": "+212", "isoCode": "MA"},
  {"name": "Mozambique", "dialCode": "+258", "isoCode": "MZ"},
  {"name": "Myanmar", "dialCode": "+95", "isoCode": "MM"},
  {"name": "Namibia", "dialCode": "+264", "isoCode": "nan"},
  {"name": "Nauru", "dialCode": "+674", "isoCode": "NR"},
  {"name": "Nepal", "dialCode": "+977", "isoCode": "NP"},
  {"name": "Netherlands", "dialCode": "+31", "isoCode": "NL"},
  {"name": "Nueva Zelanda", "dialCode": "+64", "isoCode": "NZ"},
  {"name": "Nicaragua", "dialCode": "+505", "isoCode": "NI"},
  {"name": "Níger", "dialCode": "+227", "isoCode": "NE"},
  {"name": "Nigeria", "dialCode": "+234", "isoCode": "NG"},
  {"name": "Noruega", "dialCode": "+47", "isoCode": "NO"},
  {"name": "Omán", "dialCode": "+968", "isoCode": "OM"},
  {"name": "Pakistán", "dialCode": "+92", "isoCode": "PK"},
  {"name": "Palaos", "dialCode": "+680", "isoCode": "PW"},
  {"name": "Panamá", "dialCode": "+507", "isoCode": "PA"},
  {"name": "Papúa Nueva Guinea", "dialCode": "+675", "isoCode": "PG"},
  {"name": "Paraguay", "dialCode": "+595", "isoCode": "PY"},
  {"name": "Perú", "dialCode": "+51", "isoCode": "PE"},
  {"name": "Filipinas", "dialCode": "+63", "isoCode": "PH"},
  {"name": "Polonia", "dialCode": "+48", "isoCode": "PL"},
  {"name": "Portugal", "dialCode": "+351", "isoCode": "PT"},
  {"name": "Qatar", "dialCode": "+974", "isoCode": "QA"},
  {"name": "Rumania", "dialCode": "+40", "isoCode": "RO"},
  {"name": "Rusia", "dialCode": "+7", "isoCode": "RU"},
  {"name": "Ruanda", "dialCode": "+250", "isoCode": "RW"},
  {"name": "San Cristóbal y Nieves", "dialCode": "+1", "isoCode": "KN"},
  {"name": "Santa Lucía", "dialCode": "+1", "isoCode": "LC"},
  {"name": "San Vicente y las Granadinas", "dialCode": "+1", "isoCode": "VC"},
  {"name": "Samoa", "dialCode": "+685", "isoCode": "WS"},
  {"name": "San Marino", "dialCode": "+378", "isoCode": "SM"},
  {"name": "Santo Tomé y Príncipe", "dialCode": "+239", "isoCode": "ST"},
  {"name": "Arabia Saudita", "dialCode": "+966", "isoCode": "SA"},
  {"name": "Senegal", "dialCode": "+221", "isoCode": "SN"},
  {"name": "Serbia", "dialCode": "+381", "isoCode": "RS"},
  {"name": "Seychelles", "dialCode": "+248", "isoCode": "SC"},
  {"name": "Sierra Leona", "dialCode": "+232", "isoCode": "SL"},
  {"name": "Singapur", "dialCode": "+65", "isoCode": "SG"},
  {"name": "Eslovaquia", "dialCode": "+421", "isoCode": "SK"},
  {"name": "Eslovenia", "dialCode": "+386", "isoCode": "SI"},
  {"name": "Islas Salomón", "dialCode": "+677", "isoCode": "SB"},
  {"name": "Somalia", "dialCode": "+252", "isoCode": "SO"},
  {"name": "Sudáfrica", "dialCode": "+27", "isoCode": "ZA"},
  {"name": "Corea del Sur", "dialCode": "+82", "isoCode": "KR"},
  {"name": "España", "dialCode": "+34", "isoCode": "ES"},
  {"name": "Sri Lanka", "dialCode": "+94", "isoCode": "LK"},
  {"name": "Sudán", "dialCode": "+249", "isoCode": "SD"},
  {"name": "Surinam", "dialCode": "+597", "isoCode": "SR"},
  {"name": "Suazilandia", "dialCode": "+268", "isoCode": "SZ"},
  {"name": "Suecia", "dialCode": "+46", "isoCode": "SE"},
  {"name": "Suiza", "dialCode": "+41", "isoCode": "CH"},
  {"name": "Siria", "dialCode": "+963", "isoCode": "SY"},
  {"name": "Tayikistán", "dialCode": "+992", "isoCode": "TJ"},
  {"name": "Tanzania", "dialCode": "+255", "isoCode": "TZ"},
  {"name": "Tailandia", "dialCode": "+66", "isoCode": "TH"},
  {"name": "Togo", "dialCode": "+228", "isoCode": "TG"},
  {"name": "Tonga", "dialCode": "+676", "isoCode": "TO"},
  {"name": "Trinidad y Tobago", "dialCode": "+1", "isoCode": "TT"},
  {"name": "Túnez", "dialCode": "+216", "isoCode": "TN"},
  {"name": "Turquía", "dialCode": "+90", "isoCode": "TR"},
  {"name": "Turkmenistán", "dialCode": "+993", "isoCode": "TM"},
  {"name": "Tuvalu", "dialCode": "+688", "isoCode": "TV"},
  {"name": "Uganda", "dialCode": "+256", "isoCode": "UG"},
  {"name": "Ucrania", "dialCode": "+380", "isoCode": "UA"},
  {"name": "Emiratos Árabes Unidos", "dialCode": "+971", "isoCode": "AE"},
  {"name": "Reino Unido", "dialCode": "+44", "isoCode": "GB"},
  {"name": "Estados Unidos", "dialCode": "+1", "isoCode": "US"},
  {"name": "Uruguay", "dialCode": "+598", "isoCode": "UY"},
  {"name": "Uzbekistán", "dialCode": "+998", "isoCode": "UZ"},
  {"name": "Vanuatu", "dialCode": "+678", "isoCode": "VU"},
  {"name": "Ciudad del Vaticano", "dialCode": "+379", "isoCode": "VA"},
  {"name": "Venezuela", "dialCode": "+58", "isoCode": "VE"},
  {"name": "Vietnam", "dialCode": "+84", "isoCode": "VN"},
  {"name": "Yemen", "dialCode": "+967", "isoCode": "YE"},
  {"name": "Zambia", "dialCode": "+260", "isoCode": "ZM"},
  {"name": "Zimbabue", "dialCode": "+263", "isoCode": "ZW"},
  ].map((e) => Country.from(e)).toList();
  static List<Country> _zh = [
  {"name": "阿富汗", "dialCode": "+93", "isoCode": "AF"},
  {"name": "阿尔巴尼亚", "dialCode": "+355", "isoCode": "AL"},
  {"name": "阿尔及利亚", "dialCode": "+213", "isoCode": "DZ"},
  {"name": "安道尔", "dialCode": "+376", "isoCode": "AD"},
  {"name": "安哥拉", "dialCode": "+244", "isoCode": "AO"},
  {"name": "安提瓜和巴布达", "dialCode": "+1", "isoCode": "AG"},
  {"name": "阿根廷", "dialCode": "+54", "isoCode": "AR"},
  {"name": "亚美尼亚", "dialCode": "+374", "isoCode": "AM"},
  {"name": "澳大利亚", "dialCode": "+61", "isoCode": "AU"},
  {"name": "奥地利", "dialCode": "+43", "isoCode": "AT"},
  {"name": "阿塞拜疆", "dialCode": "+994", "isoCode": "AZ"},
  {"name": "巴哈马", "dialCode": "+1", "isoCode": "BS"},
  {"name": "巴林", "dialCode": "+973", "isoCode": "BH"},
  {"name": "孟加拉国", "dialCode": "+880", "isoCode": "BD"},
  {"name": "巴巴多斯", "dialCode": "+1", "isoCode": "BB"},
  {"name": "白俄罗斯", "dialCode": "+375", "isoCode": "BY"},
  {"name": "比利时", "dialCode": "+32", "isoCode": "BE"},
  {"name": "伯利兹", "dialCode": "+501", "isoCode": "BZ"},
  {"name": "贝宁", "dialCode": "+229", "isoCode": "BJ"},
  {"name": "不丹", "dialCode": "+975", "isoCode": "BT"},
  {"name": "玻利维亚", "dialCode": "+591", "isoCode": "BO"},
  {"name": "波斯尼亚和黑塞哥维那", "dialCode": "+387", "isoCode": "BA"},
  {"name": "博茨瓦纳", "dialCode": "+267", "isoCode": "BW"},
  {"name": "巴西", "dialCode": "+55", "isoCode": "BR"},
  {"name": "文莱", "dialCode": "+673", "isoCode": "BN"},
  {"name": "保加利亚", "dialCode": "+359", "isoCode": "BG"},
  {"name": "布基纳法索", "dialCode": "+226", "isoCode": "BF"},
  {"name": "布隆迪", "dialCode": "+257", "isoCode": "BI"},
  {"name": "柬埔寨", "dialCode": "+855", "isoCode": "KH"},
  {"name": "喀麦隆", "dialCode": "+237", "isoCode": "CM"},
  {"name": "加拿大", "dialCode": "+1", "isoCode": "CA"},
  {"name": "佛得角", "dialCode": "+238", "isoCode": "CV"},
  {"name": "中非共和国", "dialCode": "+236", "isoCode": "CF"},
  {"name": "乍得", "dialCode": "+235", "isoCode": "TD"},
  {"name": "智利", "dialCode": "+56", "isoCode": "CL"},
  {"name": "中国", "dialCode": "+86", "isoCode": "CN"},
  {"name": "哥伦比亚", "dialCode": "+57", "isoCode": "CO"},
  {"name": "科摩罗", "dialCode": "+269", "isoCode": "KM"},
  {"name": "刚果（布）", "dialCode": "+242", "isoCode": "CG"},
  {"name": "刚果（金）", "dialCode": "+243", "isoCode": "CD"},
  {"name": "哥斯达黎加", "dialCode": "+506", "isoCode": "CR"},
  {"name": "克罗地亚", "dialCode": "+385", "isoCode": "HR"},
  {"name": "古巴", "dialCode": "+53", "isoCode": "CU"},
  {"name": "塞浦路斯", "dialCode": "+357", "isoCode": "CY"},
  {"name": "捷克共和国", "dialCode": "+420", "isoCode": "CZ"},
  {"name": "丹麦", "dialCode": "+45", "isoCode": "DK"},
  {"name": "吉布提", "dialCode": "+253", "isoCode": "DJ"},
  {"name": "多米尼克", "dialCode": "+1", "isoCode": "DM"},
  {"name": "多米尼加共和国", "dialCode": "+1", "isoCode": "DO"},
  {"name": "东帝汶", "dialCode": "+670", "isoCode": "TL"},
  {"name": "厄瓜多尔", "dialCode": "+593", "isoCode": "EC"},
  {"name": "埃及", "dialCode": "+20", "isoCode": "EG"},
  {"name": "萨尔瓦多", "dialCode": "+503", "isoCode": "SV"},
  {"name": "赤道几内亚", "dialCode": "+240", "isoCode": "GQ"},
  {"name": "厄立特里亚", "dialCode": "+291", "isoCode": "ER"},
  {"name": "爱沙尼亚", "dialCode": "+372", "isoCode": "EE"},
  {"name": "埃塞俄比亚", "dialCode": "+251", "isoCode": "ET"},
  {"name": "斐济", "dialCode": "+679", "isoCode": "FJ"},
  {"name": "芬兰", "dialCode": "+358", "isoCode": "FI"},
  {"name": "法国", "dialCode": "+33", "isoCode": "FR"},
  {"name": "加蓬", "dialCode": "+241", "isoCode": "GA"},
  {"name": "冈比亚", "dialCode": "+220", "isoCode": "GM"},
  {"name": "格鲁吉亚", "dialCode": "+995", "isoCode": "GE"},
  {"name": "德国", "dialCode": "+49", "isoCode": "DE"},
  {"name": "加纳", "dialCode": "+233", "isoCode": "GH"},
  {"name": "希腊", "dialCode": "+30", "isoCode": "GR"},
  {"name": "格林纳达", "dialCode": "+1", "isoCode": "GD"},
  {"name": "危地马拉", "dialCode": "+502", "isoCode": "GT"},
  {"name": "几内亚", "dialCode": "+224", "isoCode": "GN"},
  {"name": "几内亚比绍", "dialCode": "+245", "isoCode": "GW"},
  {"name": "圭亚那", "dialCode": "+592", "isoCode": "GY"},
  {"name": "海地", "dialCode": "+509", "isoCode": "HT"},
  {"name": "洪都拉斯", "dialCode": "+504", "isoCode": "HN"},
  {"name": "匈牙利", "dialCode": "+36", "isoCode": "HU"},
  {"name": "冰岛", "dialCode": "+354", "isoCode": "IS"},
  {"name": "印度", "dialCode": "+91", "isoCode": "IN"},
  {"name": "印度尼西亚", "dialCode": "+62", "isoCode": "ID"},
  {"name": "伊朗", "dialCode": "+98", "isoCode": "IR"},
  {"name": "伊拉克", "dialCode": "+964", "isoCode": "IQ"},
  {"name": "爱尔兰", "dialCode": "+353", "isoCode": "IE"},
  {"name": "以色列", "dialCode": "+972", "isoCode": "IL"},
  {"name": "意大利", "dialCode": "+39", "isoCode": "IT"},
  {"name": "牙买加", "dialCode": "+1", "isoCode": "JM"},
  {"name": "日本", "dialCode": "+81", "isoCode": "JP"},
  {"name": "约旦", "dialCode": "+962", "isoCode": "JO"},
  {"name": "哈萨克斯坦", "dialCode": "+7", "isoCode": "KZ"},
  {"name": "肯尼亚", "dialCode": "+254", "isoCode": "KE"},
  {"name": "基里巴斯", "dialCode": "+686", "isoCode": "KI"},
  {"name": "科威特", "dialCode": "+965", "isoCode": "KW"},
  {"name": "吉尔吉斯斯坦", "dialCode": "+996", "isoCode": "KG"},
  {"name": "老挝", "dialCode": "+856", "isoCode": "LA"},
  {"name": "拉脱维亚", "dialCode": "+371", "isoCode": "LV"},
  {"name": "黎巴嫩", "dialCode": "+961", "isoCode": "LB"},
  {"name": "莱索托", "dialCode": "+266", "isoCode": "LS"},
  {"name": "利比里亚", "dialCode": "+231", "isoCode": "LR"},
  {"name": "利比亚", "dialCode": "+218", "isoCode": "LY"},
  {"name": "列支敦士登", "dialCode": "+423", "isoCode": "LI"},
  {"name": "立陶宛", "dialCode": "+370", "isoCode": "LT"},
  {"name": "卢森堡", "dialCode": "+352", "isoCode": "LU"},
  {"name": "马其顿", "dialCode": "+389", "isoCode": "MK"},
  {"name": "马达加斯加", "dialCode": "+261", "isoCode": "MG"},
  {"name": "马拉维", "dialCode": "+265", "isoCode": "MW"},
  {"name": "马来西亚", "dialCode": "+60", "isoCode": "MY"},
  {"name": "马尔代夫", "dialCode": "+960", "isoCode": "MV"},
  {"name": "马里", "dialCode": "+223", "isoCode": "ML"},
  {"name": "马耳他", "dialCode": "+356", "isoCode": "MT"},
  {"name": "马绍尔群岛", "dialCode": "+692", "isoCode": "MH"},
  {"name": "毛里塔尼亚", "dialCode": "+222", "isoCode": "MR"},
  {"name": "毛里求斯", "dialCode": "+230", "isoCode": "MU"},
  {"name": "墨西哥", "dialCode": "+52", "isoCode": "MX"},
  {"name": "密克罗尼西亚", "dialCode": "+691", "isoCode": "FM"},
  {"name": "摩尔多瓦", "dialCode": "+373", "isoCode": "MD"},
  {"name": "摩纳哥", "dialCode": "+377", "isoCode": "MC"},
  {"name": "蒙古", "dialCode": "+976", "isoCode": "MN"},
  {"name": "黑山", "dialCode": "+382", "isoCode": "ME"},
  {"name": "摩洛哥", "dialCode": "+212", "isoCode": "MA"},
  {"name": "莫桑比克", "dialCode": "+258", "isoCode": "MZ"},
  {"name": "缅甸", "dialCode": "+95", "isoCode": "MM"},
  {"name": "纳米比亚", "dialCode": "+264", "isoCode": "nan"},
  {"name": "瑙鲁", "dialCode": "+674", "isoCode": "NR"},
  {"name": "尼泊尔", "dialCode": "+977", "isoCode": "NP"},
  {"name": "荷兰", "dialCode": "+31", "isoCode": "NL"},
  {"name": "新西兰", "dialCode": "+64", "isoCode": "NZ"},
  {"name": "尼加拉瓜", "dialCode": "+505", "isoCode": "NI"},
  {"name": "尼日尔", "dialCode": "+227", "isoCode": "NE"},
  {"name": "尼日利亚", "dialCode": "+234", "isoCode": "NG"},
  {"name": "挪威", "dialCode": "+47", "isoCode": "NO"},
  {"name": "阿曼", "dialCode": "+968", "isoCode": "OM"},
  {"name": "巴基斯坦", "dialCode": "+92", "isoCode": "PK"},
  {"name": "帕劳", "dialCode": "+680", "isoCode": "PW"},
  {"name": "巴拿马", "dialCode": "+507", "isoCode": "PA"},
  {"name": "巴布亚新几内亚", "dialCode": "+675", "isoCode": "PG"},
  {"name": "巴拉圭", "dialCode": "+595", "isoCode": "PY"},
  {"name": "秘鲁", "dialCode": "+51", "isoCode": "PE"},
  {"name": "菲律宾", "dialCode": "+63", "isoCode": "PH"},
  {"name": "波兰", "dialCode": "+48", "isoCode": "PL"},
  {"name": "葡萄牙", "dialCode": "+351", "isoCode": "PT"},
  {"name": "卡塔尔", "dialCode": "+974", "isoCode": "QA"},
  {"name": "罗马尼亚", "dialCode": "+40", "isoCode": "RO"},
  {"name": "俄罗斯", "dialCode": "+7", "isoCode": "RU"},
  {"name": "卢旺达", "dialCode": "+250", "isoCode": "RW"},
  {"name": "圣基茨和尼维斯", "dialCode": "+1", "isoCode": "KN"},
  {"name": "圣卢西亚", "dialCode": "+1", "isoCode": "LC"},
  {"name": "圣文森特和格林纳丁斯", "dialCode": "+1", "isoCode": "VC"},
  {"name": "萨摩亚", "dialCode": "+685", "isoCode": "WS"},
  {"name": "圣马力诺", "dialCode": "+378", "isoCode": "SM"},
  {"name": "圣多美和普林西比", "dialCode": "+239", "isoCode": "ST"},
  {"name": "沙特阿拉伯", "dialCode": "+966", "isoCode": "SA"},
  {"name": "塞内加尔", "dialCode": "+221", "isoCode": "SN"},
  {"name": "塞尔维亚", "dialCode": "+381", "isoCode": "RS"},
  {"name": "塞舌尔", "dialCode": "+248", "isoCode": "SC"},
  {"name": "塞拉利昂", "dialCode": "+232", "isoCode": "SL"},
  {"name": "新加坡", "dialCode": "+65", "isoCode": "SG"},
  {"name": "斯洛伐克", "dialCode": "+421", "isoCode": "SK"},
  {"name": "斯洛文尼亚", "dialCode": "+386", "isoCode": "SI"},
  {"name": "所罗门群岛", "dialCode": "+677", "isoCode": "SB"},
  {"name": "索马里", "dialCode": "+252", "isoCode": "SO"},
  {"name": "南非", "dialCode": "+27", "isoCode": "ZA"},
  {"name": "韩国", "dialCode": "+82", "isoCode": "KR"},
  {"name": "西班牙", "dialCode": "+34", "isoCode": "ES"},
  {"name": "斯里兰卡", "dialCode": "+94", "isoCode": "LK"},
  {"name": "苏丹", "dialCode": "+249", "isoCode": "SD"},
  {"name": "苏里南", "dialCode": "+597", "isoCode": "SR"},
  {"name": "斯威士兰", "dialCode": "+268", "isoCode": "SZ"},
  {"name": "瑞典", "dialCode": "+46", "isoCode": "SE"},
  {"name": "瑞士", "dialCode": "+41", "isoCode": "CH"},
  {"name": "叙利亚", "dialCode": "+963", "isoCode": "SY"},
  {"name": "塔吉克斯坦", "dialCode": "+992", "isoCode": "TJ"},
  {"name": "坦桑尼亚", "dialCode": "+255", "isoCode": "TZ"},
  {"name": "泰国", "dialCode": "+66", "isoCode": "TH"},
  {"name": "多哥", "dialCode": "+228", "isoCode": "TG"},
  {"name": "汤加", "dialCode": "+676", "isoCode": "TO"},
  {"name": "特立尼达和多巴哥", "dialCode": "+1", "isoCode": "TT"},
  {"name": "突尼斯", "dialCode": "+216", "isoCode": "TN"},
  {"name": "土耳其", "dialCode": "+90", "isoCode": "TR"},
  {"name": "土库曼斯坦", "dialCode": "+993", "isoCode": "TM"},
  {"name": "图瓦卢", "dialCode": "+688", "isoCode": "TV"},
  {"name": "乌干达", "dialCode": "+256", "isoCode": "UG"},
  {"name": "乌克兰", "dialCode": "+380", "isoCode": "UA"},
  {"name": "阿拉伯联合酋长国", "dialCode": "+971", "isoCode": "AE"},
  {"name": "英国", "dialCode": "+44", "isoCode": "GB"},
  {"name": "美国", "dialCode": "+1", "isoCode": "US"},
  {"name": "乌拉圭", "dialCode": "+598", "isoCode": "UY"},
  {"name": "乌兹别克斯坦", "dialCode": "+998", "isoCode": "UZ"},
  {"name": "瓦努阿图", "dialCode": "+678", "isoCode": "VU"},
  {"name": "梵蒂冈城", "dialCode": "+379", "isoCode": "VA"},
  {"name": "委内瑞拉", "dialCode": "+58", "isoCode": "VE"},
  {"name": "越南", "dialCode": "+84", "isoCode": "VN"},
  {"name": "也门", "dialCode": "+967", "isoCode": "YE"},
  {"name": "赞比亚", "dialCode": "+260", "isoCode": "ZM"},
  {"name": "津巴布韦", "dialCode": "+263", "isoCode": "ZW"},
  ].map((e) => Country.from(e)).toList();
  static List<Country> _ar = [
  {"name": "أفغانستان", "dialCode": "+93", "isoCode": "AF"},
  {"name": "ألبانيا", "dialCode": "+355", "isoCode": "AL"},
  {"name": "الجزائر", "dialCode": "+213", "isoCode": "DZ"},
  {"name": "أندورا", "dialCode": "+376", "isoCode": "AD"},
  {"name": "أنغولا", "dialCode": "+244", "isoCode": "AO"},
  {"name": "أنتيغوا وباربودا", "dialCode": "+1", "isoCode": "AG"},
  {"name": "الأرجنتين", "dialCode": "+54", "isoCode": "AR"},
  {"name": "أرمينيا", "dialCode": "+374", "isoCode": "AM"},
  {"name": "أستراليا", "dialCode": "+61", "isoCode": "AU"},
  {"name": "النمسا", "dialCode": "+43", "isoCode": "AT"},
  {"name": "أذربيجان", "dialCode": "+994", "isoCode": "AZ"},
  {"name": "البهاماس", "dialCode": "+1", "isoCode": "BS"},
  {"name": "البحرين", "dialCode": "+973", "isoCode": "BH"},
  {"name": "بنغلاديش", "dialCode": "+880", "isoCode": "BD"},
  {"name": "بربادوس", "dialCode": "+1", "isoCode": "BB"},
  {"name": "روسيا البيضاء", "dialCode": "+375", "isoCode": "BY"},
  {"name": "بلجيكا", "dialCode": "+32", "isoCode": "BE"},
  {"name": "بليز", "dialCode": "+501", "isoCode": "BZ"},
  {"name": "بنين", "dialCode": "+229", "isoCode": "BJ"},
  {"name": "بوتان", "dialCode": "+975", "isoCode": "BT"},
  {"name": "بوليفيا", "dialCode": "+591", "isoCode": "BO"},
  {"name": "البوسنة والهرسك", "dialCode": "+387", "isoCode": "BA"},
  {"name": "بوتسوانا", "dialCode": "+267", "isoCode": "BW"},
  {"name": "البرازيل", "dialCode": "+55", "isoCode": "BR"},
  {"name": "بروناي", "dialCode": "+673", "isoCode": "BN"},
  {"name": "بلغاريا", "dialCode": "+359", "isoCode": "BG"},
  {"name": "بوركينا فاسو", "dialCode": "+226", "isoCode": "BF"},
  {"name": "بوروندي", "dialCode": "+257", "isoCode": "BI"},
  {"name": "كمبوديا", "dialCode": "+855", "isoCode": "KH"},
  {"name": "الكاميرون", "dialCode": "+237", "isoCode": "CM"},
  {"name": "كندا", "dialCode": "+1", "isoCode": "CA"},
  {"name": "الرأس الأخضر", "dialCode": "+238", "isoCode": "CV"},
  {"name": "جمهورية أفريقيا الوسطى", "dialCode": "+236", "isoCode": "CF"},
  {"name": "تشاد", "dialCode": "+235", "isoCode": "TD"},
  {"name": "تشيلي", "dialCode": "+56", "isoCode": "CL"},
  {"name": "الصين", "dialCode": "+86", "isoCode": "CN"},
  {"name": "كولومبيا", "dialCode": "+57", "isoCode": "CO"},
  {"name": "جزر القمر", "dialCode": "+269", "isoCode": "KM"},
  {"name": "جمهورية الكونغو الديمقراطية", "dialCode": "+242", "isoCode": "CG"},
  {"name": "جمهورية الكونغو الديمقراطية", "dialCode": "+243", "isoCode": "CD"},
  {"name": "كوستاريكا", "dialCode": "+506", "isoCode": "CR"},
  {"name": "كرواتيا", "dialCode": "+385", "isoCode": "HR"},
  {"name": "كوبا", "dialCode": "+53", "isoCode": "CU"},
  {"name": "قبرص", "dialCode": "+357", "isoCode": "CY"},
  {"name": "جمهورية التشيك", "dialCode": "+420", "isoCode": "CZ"},
  {"name": "الدنمارك", "dialCode": "+45", "isoCode": "DK"},
  {"name": "جيبوتي", "dialCode": "+253", "isoCode": "DJ"},
  {"name": "دومينيكا", "dialCode": "+1", "isoCode": "DM"},
  {"name": "جمهورية الدومينيكان", "dialCode": "+1", "isoCode": "DO"},
  {"name": "تيمور الشرقية", "dialCode": "+670", "isoCode": "TL"},
  {"name": "الإكوادور", "dialCode": "+593", "isoCode": "EC"},
  {"name": "مصر", "dialCode": "+20", "isoCode": "EG"},
  {"name": "السلفادور", "dialCode": "+503", "isoCode": "SV"},
  {"name": "غينيا الاستوائية", "dialCode": "+240", "isoCode": "GQ"},
  {"name": "إريتريا", "dialCode": "+291", "isoCode": "ER"},
  {"name": "إستونيا", "dialCode": "+372", "isoCode": "EE"},
  {"name": "إثيوبيا", "dialCode": "+251", "isoCode": "ET"},
  {"name": "فيجي", "dialCode": "+679", "isoCode": "FJ"},
  {"name": "فنلندا", "dialCode": "+358", "isoCode": "FI"},
  {"name": "فرنسا", "dialCode": "+33", "isoCode": "FR"},
  {"name": "الغابون", "dialCode": "+241", "isoCode": "GA"},
  {"name": "غامبيا", "dialCode": "+220", "isoCode": "GM"},
  {"name": "جورجيا", "dialCode": "+995", "isoCode": "GE"},
  {"name": "ألمانيا", "dialCode": "+49", "isoCode": "DE"},
  {"name": "غانا", "dialCode": "+233", "isoCode": "GH"},
  {"name": "اليونان", "dialCode": "+30", "isoCode": "GR"},
  {"name": "غرينادا", "dialCode": "+1", "isoCode": "GD"},
  {"name": "غواتيمالا", "dialCode": "+502", "isoCode": "GT"},
  {"name": "غينيا", "dialCode": "+224", "isoCode": "GN"},
  {"name": "غينيا بيساو", "dialCode": "+245", "isoCode": "GW"},
  {"name": "غيانا", "dialCode": "+592", "isoCode": "GY"},
  {"name": "هايتي", "dialCode": "+509", "isoCode": "HT"},
  {"name": "هندوراس", "dialCode": "+504", "isoCode": "HN"},
  {"name": "هنغاريا", "dialCode": "+36", "isoCode": "HU"},
  {"name": "أيسلندا", "dialCode": "+354", "isoCode": "IS"},
  {"name": "الهند", "dialCode": "+91", "isoCode": "IN"},
  {"name": "إندونيسيا", "dialCode": "+62", "isoCode": "ID"},
  {"name": "إيران", "dialCode": "+98", "isoCode": "IR"},
  {"name": "العراق", "dialCode": "+964", "isoCode": "IQ"},
  {"name": "أيرلندا", "dialCode": "+353", "isoCode": "IE"},
  {"name": "إسرائيل", "dialCode": "+972", "isoCode": "IL"},
  {"name": "إيطاليا", "dialCode": "+39", "isoCode": "IT"},
  {"name": "جامايكا", "dialCode": "+1", "isoCode": "JM"},
  {"name": "اليابان", "dialCode": "+81", "isoCode": "JP"},
  {"name": "الأردن", "dialCode": "+962", "isoCode": "JO"},
  {"name": "كازاخستان", "dialCode": "+7", "isoCode": "KZ"},
  {"name": "كينيا", "dialCode": "+254", "isoCode": "KE"},
  {"name": "كيريباتي", "dialCode": "+686", "isoCode": "KI"},
  {"name": "الكويت", "dialCode": "+965", "isoCode": "KW"},
  {"name": "قرغيزستان", "dialCode": "+996", "isoCode": "KG"},
  {"name": "لاوس", "dialCode": "+856", "isoCode": "LA"},
  {"name": "لاتفيا", "dialCode": "+371", "isoCode": "LV"},
  {"name": "لبنان", "dialCode": "+961", "isoCode": "LB"},
  {"name": "ليسوتو", "dialCode": "+266", "isoCode": "LS"},
  {"name": "ليبيريا", "dialCode": "+231", "isoCode": "LR"},
  {"name": "ليبيا", "dialCode": "+218", "isoCode": "LY"},
  {"name": "ليختنشتاين", "dialCode": "+423", "isoCode": "LI"},
  {"name": "ليتوانيا", "dialCode": "+370", "isoCode": "LT"},
  {"name": "لوكسمبورغ", "dialCode": "+352", "isoCode": "LU"},
  {"name": "مقدونيا", "dialCode": "+389", "isoCode": "MK"},
  {"name": "مدغشقر", "dialCode": "+261", "isoCode": "MG"},
  {"name": "مالاوي", "dialCode": "+265", "isoCode": "MW"},
  {"name": "ماليزيا", "dialCode": "+60", "isoCode": "MY"},
  {"name": "المالديف", "dialCode": "+960", "isoCode": "MV"},
  {"name": "مالي", "dialCode": "+223", "isoCode": "ML"},
  {"name": "مالطا", "dialCode": "+356", "isoCode": "MT"},
  {"name": "جزر مارشال", "dialCode": "+692", "isoCode": "MH"},
  {"name": "موريتانيا", "dialCode": "+222", "isoCode": "MR"},
  {"name": "موريشيوس", "dialCode": "+230", "isoCode": "MU"},
  {"name": "المكسيك", "dialCode": "+52", "isoCode": "MX"},
  {"name": "ميكرونيزيا", "dialCode": "+691", "isoCode": "FM"},
  {"name": "مولدوفا", "dialCode": "+373", "isoCode": "MD"},
  {"name": "موناكو", "dialCode": "+377", "isoCode": "MC"},
  {"name": "منغوليا", "dialCode": "+976", "isoCode": "MN"},
  {"name": "الجبل الأسود", "dialCode": "+382", "isoCode": "ME"},
  {"name": "المغرب", "dialCode": "+212", "isoCode": "MA"},
  {"name": "موزمبيق", "dialCode": "+258", "isoCode": "MZ"},
  {"name": "ميانمار (بورما)", "dialCode": "+95", "isoCode": "MM"},
  {"name": "ناميبيا", "dialCode": "+264", "isoCode": "nan"},
  {"name": "ناورو", "dialCode": "+674", "isoCode": "NR"},
  {"name": "نيبال", "dialCode": "+977", "isoCode": "NP"},
  {"name": "هولندا", "dialCode": "+31", "isoCode": "NL"},
  {"name": "نيوزيلندا", "dialCode": "+64", "isoCode": "NZ"},
  {"name": "نيكاراغوا", "dialCode": "+505", "isoCode": "NI"},
  {"name": "النيجر", "dialCode": "+227", "isoCode": "NE"},
  {"name": "نيجيريا", "dialCode": "+234", "isoCode": "NG"},
  {"name": "النرويج", "dialCode": "+47", "isoCode": "NO"},
  {"name": "عمان", "dialCode": "+968", "isoCode": "OM"},
  {"name": "باكستان", "dialCode": "+92", "isoCode": "PK"},
  {"name": "بالاو", "dialCode": "+680", "isoCode": "PW"},
  {"name": "بنما", "dialCode": "+507", "isoCode": "PA"},
  {"name": "بابوا غينيا الجديدة", "dialCode": "+675", "isoCode": "PG"},
  {"name": "باراغواي", "dialCode": "+595", "isoCode": "PY"},
  {"name": "بيرو", "dialCode": "+51", "isoCode": "PE"},
  {"name": "الفلبين", "dialCode": "+63", "isoCode": "PH"},
  {"name": "بولندا", "dialCode": "+48", "isoCode": "PL"},
  {"name": "البرتغال", "dialCode": "+351", "isoCode": "PT"},
  {"name": "قطر", "dialCode": "+974", "isoCode": "QA"},
  {"name": "رومانيا", "dialCode": "+40", "isoCode": "RO"},
  {"name": "روسيا", "dialCode": "+7", "isoCode": "RU"},
  {"name": "رواندا", "dialCode": "+250", "isoCode": "RW"},
  {"name": "سانت كيتس ونيفيس", "dialCode": "+1", "isoCode": "KN"},
  {"name": "سانت لوسيا", "dialCode": "+1", "isoCode": "LC"},
  {"name": "سانت فنسنت وجزر غرينادين", "dialCode": "+1", "isoCode": "VC"},
  {"name": "ساموا", "dialCode": "+685", "isoCode": "WS"},
  {"name": "سان مارينو", "dialCode": "+378", "isoCode": "SM"},
  {"name": "ساو تومي وبرينسيبي", "dialCode": "+239", "isoCode": "ST"},
  {"name": "المملكة العربية السعودية", "dialCode": "+966", "isoCode": "SA"},
  {"name": "السنغال", "dialCode": "+221", "isoCode": "SN"},
  {"name": "صربيا", "dialCode": "+381", "isoCode": "RS"},
  {"name": "سيشل", "dialCode": "+248", "isoCode": "SC"},
  {"name": "سيراليون", "dialCode": "+232", "isoCode": "SL"},
  {"name": "سنغافورة", "dialCode": "+65", "isoCode": "SG"},
  {"name": "سلوفاكيا", "dialCode": "+421", "isoCode": "SK"},
  {"name": "سلوفينيا", "dialCode": "+386", "isoCode": "SI"},
  {"name": "جزر سليمان", "dialCode": "+677", "isoCode": "SB"},
  {"name": "الصومال", "dialCode": "+252", "isoCode": "SO"},
  {"name": "جنوب أفريقيا", "dialCode": "+27", "isoCode": "ZA"},
  {"name": "كوريا الجنوبية", "dialCode": "+82", "isoCode": "KR"},
  {"name": "إسبانيا", "dialCode": "+34", "isoCode": "ES"},
  {"name": "سريلانكا", "dialCode": "+94", "isoCode": "LK"},
  {"name": "السودان", "dialCode": "+249", "isoCode": "SD"},
  {"name": "سورينام", "dialCode": "+597", "isoCode": "SR"},
  {"name": "سوازيلاند", "dialCode": "+268", "isoCode": "SZ"},
  {"name": "السويد", "dialCode": "+46", "isoCode": "SE"},
  {"name": "سويسرا", "dialCode": "+41", "isoCode": "CH"},
  {"name": "سوريا", "dialCode": "+963", "isoCode": "SY"},
  {"name": "طاجيكستان", "dialCode": "+992", "isoCode": "TJ"},
  {"name": "تنزانيا", "dialCode": "+255", "isoCode": "TZ"},
  {"name": "تايلاند", "dialCode": "+66", "isoCode": "TH"},
  {"name": "توغو", "dialCode": "+228", "isoCode": "TG"},
  {"name": "تونغا", "dialCode": "+676", "isoCode": "TO"},
  {"name": "ترينيداد وتوباغو", "dialCode": "+1", "isoCode": "TT"},
  {"name": "تونس", "dialCode": "+216", "isoCode": "TN"},
  {"name": "تركيا", "dialCode": "+90", "isoCode": "TR"},
  {"name": "تركمانستان", "dialCode": "+993", "isoCode": "TM"},
  {"name": "توفالو", "dialCode": "+688", "isoCode": "TV"},
  {"name": "أوغندا", "dialCode": "+256", "isoCode": "UG"},
  {"name": "أوكرانيا", "dialCode": "+380", "isoCode": "UA"},
  {"name": "الإمارات العربية المتحدة", "dialCode": "+971", "isoCode": "AE"},
  {"name": "المملكة المتحدة", "dialCode": "+44", "isoCode": "GB"},
  {"name": "الولايات المتحدة الأمريكية", "dialCode": "+1", "isoCode": "US"},
  {"name": "أوروغواي", "dialCode": "+598", "isoCode": "UY"},
  {"name": "أوزبكستان", "dialCode": "+998", "isoCode": "UZ"},
  {"name": "فانواتو", "dialCode": "+678", "isoCode": "VU"},
  {"name": "الفاتيكان", "dialCode": "+379", "isoCode": "VA"},
  {"name": "فنزويلا", "dialCode": "+58", "isoCode": "VE"},
  {"name": "فيتنام", "dialCode": "+84", "isoCode": "VN"},
  {"name": "اليمن", "dialCode": "+967", "isoCode": "YE"},
  {"name": "زامبيا", "dialCode": "+260", "isoCode": "ZM"},
  {"name": "زيمبابوي", "dialCode": "+263", "isoCode": "ZW"},
  ].map((e) => Country.from(e)).toList();

}
